export const ArabicAppModules = {
  "modules.MUNICIPALITIES": "البلديات",
  "modules.DEPARTMENTS": "الأقسام",
  "modules.GROUPS": "المجموعات",
  "modules.POSITIONS": "المسمي الوظيفي",
  "modules.OWNERS": "الملاك",
  "modules.NATIONALITIES": "الجنسيات",
  "modules.NATIONALIDTYPES": "انواع الهويات",
  "modules.COMMITTEES": "اللجان الفنية",
  "modules.ENGINEERING_COMPANIES": "المكاتب الهندسية المعتمدة",
  "modules.ISSUERS": "جهات الاصدار",
  "modules.ISSUERS_TYPE": "انواع جهات الاصدار",
  "modules.WORKFLOW_TITLE": "مسمي مسار العمل",
  "modules.USER_TITLE": "المستخدمين",
  "modules.CREATE_REQUEST": "معاملة جديدة",
  "modules.CREATE_ORDERING": "تعميم جديد",
  "modules.RUNNING_SUBMISSIONS": "المعاملات الواردة",
  "modules.RUNNING_ORDERING": "التعميمات الواردة",
  "modules.RETURNED_SUBMISSION": "المعاملات المعادة",
  "modules.REJECTED_SUBMISSION": "المعاملات المعتذر عنها",
  "modules.DRAFT_SUBMISSIONS": "معاملات تحت التجهيز",
  "modules.ARCHIVED_SUBMISSION": "الأرشيف",
  "modules.CAD_EXPORT": "استيراد ملف رسم الهندسي (اوتوكاد)",
  "modules.REQUESTED_SUBMISSION": "المعاملات الصادرة",
  "modules.REQUESTED_ORDERING": "التعميمات الصادرة",
  "modules.SCALATION": "المعاملات المتأخرة",
  "modules.MAPVIEWER": "المستكشف الجغرافي",
  "modules.APPLICATIONS": "التطبيقات",
  "modules.DEFAULT": "الرئيسية",
  "modules.NEWS": "الأخبار",
  "modules.RATING": "التقييمات",
  "modules.QUESTIONS": "الأسئلة",
  "modules.STATISTICS": "الإحصائيات",
  "modules.INVESTMENT_STATISTICS": "مؤشرات",
  "modules.INVESTMENT_INDICATORS": "مؤشرات الاستثمار",
  "modules.PORTAL.POLL": "تقييمات البوابة",
  // "modules.APPROVAL": "",
  "modules.SUB_MUNICIPILTY": "البلديات الفرعية",
  "modules.SPLIT_STATISTICS": "إحصائيات الفرز",
  "modules.FINISH_SUBMISSION": "المعاملات المنتهية",
  "modules.ENGCOM_STATISTICS": "إحصائيات المكتب الهندسي",
  "modules.REVIEW_REQUESTS": "طلبات الاعتماد",
  "modules.MAP_OBJECT_ID_IDENTIFICATION": "",
  // "modules.USEROWNERS": "",
  "modules.ENG_COMP_FREEZE": "المكاتب الهندسية المجمدة",
  "modules.PAYED_SUBMISSIONS": "المعاملات المدفوعة (الجاهزة للطباعة)",
  "modules.UNPAYED_SUBMISSIONS": "المعاملات المعلقة",
  "modules.INFORMATION_PANEL": "لوحة المعلومات",
  "modules.TRANSFERED_SUBMISSIONS": "المعاملات المحولة",
  "modules.ENGCOMP_ALERTS": "انذارات المكتب الهندسي",
  "modules.MARSAD_MAPVIEWER": "المرصد الحضري بالمستكشف الجغرافي",
  "modules.WASFY_SEARCH_MAPVIEWER":
    "البحث بالبيانات الوصفية بالمستكشف الجغرافي",
  "modules.EXPORT_CADFILE_MAPVIEWER": "استيراد الملفات بالمستكشف الجغرافي",
  "modules.UNSIGNED_SUBMISSIONS": "المعاملات الغير معتمدة",
  "modules.IS_PUBLIC_MAPVIEWER": "العامة للمستكشف الجغرافي",
  "modules.IS_EMPOLYEE_MAPVIEWER": "الموظفين للمستكشف الجغرافي",
  "modules.SIGNED_SUBMISSIONS": "المعاملات المعتمدة",
};
export const Arabic_step_actions = {
  "global.SENDAMANA": "ارسال الى الامانة",
  "global.ASSIGN": "توجيه",
  "global.VERIFY": "تأكيد",
  "global.RETURNFROMSTART": "اعادة توجيه مع اعادة المسار ",
  "global.TRANSFER": "تحويل",
  "global.ASSIGNMULTI": " توجيه لمتعدد",
  "global.REJECT": "اعتذار",
  "global.SUBMIT": "ارسال",
  "global.RETURN": "اعادة توجيه",
  "global.GOTO": "مخاطبة",
  "global.APPROVE": "موافقه و توجيه الى",
  انهاء: "انهاء",
  "global.FINISH": "انهاء",
  "global.STOP": "ايقاف",
  "global.BACK": "السابق",
  // "global.TRANSFER": "ايقاف",
};