import { host } from "imports/config";
export default {
  label: "بيانات مرحلة الإشراف",
  sections: {
    supervision_attachments: {
      label: "بيانات مرحلة الإشراف",
      fields: {
        Type_of_project_resources_communication: {
          label: "بيان التواصل لأطراف المشروع  نوعه",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Tatweer_stage: {
          label: "بيان مرحلة التطوير",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Disclaimers: {
          label: "محاضر وإخلاءات الطرف الاخرى",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Material_approvals: {
          label: "اعتمادات المواد",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Full_designed_plans: {
          label: "المخططات التصميمة كاملة",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".DWG,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Full_executed_plans: {
          label: "المخططات التنفيذية كاملة",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".DWG,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Obstacles_solutions: {
          label: "المعوقات والحلول",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Performance_evaluations: {
          label: "تقييمات الاداء",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: ".docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        Bank_Guarantee: {
          label: "الضمان البنكي",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.docx,.doc,.pdf",
          multiple: false,
          required: false,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
      },
    },
    supervision_letter: {
      label: "بيانات خطاب الإدارة العامة لإشراف",
      fields: {
        supervision_letter_num: {
          required: true,
          label: "رقم خطاب الإدارة العامة لإشراف",
          field: "text",
        },
        supervision_letter_date: {
          field: "hijriDatePicker",
          lessThanToday: true,
          required: true,
          label: "تاريخ خطاب الإدارة العامة لإشراف",
        },
        supervision_letter_attachment: {
          label: "مرفق خطاب الإدارة العامة لإشراف",
          required: true,
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          // required: true,
          maxNumOfFiles: 1,
        },
      },
    },
  },
};
