export const planObjects = [
    { identfiy_parcel: "landData" },
    { suggestion_survayreport: "data_msa7y" },
    { suggestionGov_survayreport: "plans" },
    { search_survey_report: "submission_data" },
    { owners_data: "ownerData" },
    { govAuthorities_approvals: "requests" },
    { contracts_data: "waseka" },
    { eng_create_remark: "approvalSubmissionNotes" },
    { bands_approval: "bda2l" },
    { lgnah_remarks: "lagna_notes" },
    { printed_remarks: "print_notes" },
    { remark_technical: "lagna_karar" },
    { plan_nitry_suggestion: "tabtiriPlans" },
    { admission_ctrl: "admissions" },
    { remarks: "remarks" },
    { comments: "comments" },
];