export const testCommentObj = [
  {
      "comment": "التعليقات الخاصة بخطوة مراجعة و تدقيق المعاملة",
      "user": {
          "id": 756,
          "name": "مراجع المعاملات",
          "email": "b@b.com",
          "phone": null,
          "address": "Cairo",
          "department_id": 1929,
          "remarks": "hagsdjgadjgajdgjagd",
          "province_id": 2,
          "minicipality_id": null,
          "engcompany_id": null,
          "issuer_id": null,
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYXNhZWVkIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3NTYiLCJleHAiOjE2Mzk5OTg2NDR9.YHOaceXDe_TXVAdkbZAZIljCEuVn0U2oJ1cOSj4vzw8",
          "position_id": 1970,
          "is_active": 1,
          "reset_token": null,
          "create_at": "6/10/1421",
          "update_at": "6/10/1421",
          "is_workflow_admin": 1,
          "image": "/GISAPI///SubAttachments/profile/OWNERIDFILE/uploadfile/ae1c5695-1502-4083-9952-8c9e176c120b.jpeg",
          "owner_id": null,
          "issuers": null,
          "departments": {
              "id": 1929,
              "name": "إدارة ضبط التنمية",
              "users": null,
              "flag": null,
              "approving_dep": null
          },
          "engineering_companies": null,
          "municipalities": null,
          "provinces": null,
          "status": null,
          "mobile": "1",
          "imageGenerate": null,
          "groups": [
              {
                  "id": 1830,
                  "name": "المراجعين",
                  "create_at": "19/01/1437",
                  "updateat": null,
                  "groups_permissions": [
                      {
                          "id": 6081,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 22,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 22,
                              "name": "modules.SCALATION",
                              "can_edit": 0,
                              "settings": null,
                              "index": 7,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false,
                              "modules": {
                                  "SCALATION": {
                                      "id": 6081,
                                      "name": "modules.SCALATION",
                                      "can_edit": 0,
                                      "settings": null,
                                      "index": 7,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 22,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "UNPAYED_SUBMISSIONS": {
                                      "id": 6082,
                                      "name": "modules.UNPAYED_SUBMISSIONS",
                                      "can_edit": 0,
                                      "settings": "municipalitySettings",
                                      "index": 5,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 43,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "PAYED_SUBMISSIONS": {
                                      "id": 6083,
                                      "name": "modules.PAYED_SUBMISSIONS",
                                      "can_edit": 0,
                                      "settings": "municipalitySettings",
                                      "index": 5,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 42,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "RETURNED_SUBMISSION": {
                                      "id": 6084,
                                      "name": "modules.RETURNED_SUBMISSION",
                                      "can_edit": 0,
                                      "settings": null,
                                      "index": 3,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 16,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "SPLIT_STATISTICS": {
                                      "id": 6085,
                                      "name": "modules.SPLIT_STATISTICS",
                                      "can_edit": null,
                                      "settings": null,
                                      "index": null,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 35,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "RATING": {
                                      "id": 6087,
                                      "name": "modules.RATING",
                                      "can_edit": null,
                                      "settings": null,
                                      "index": 7,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 27,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "ARCHIVED_SUBMISSION": {
                                      "id": 6088,
                                      "name": "modules.ARCHIVED_SUBMISSION",
                                      "can_edit": 0,
                                      "settings": null,
                                      "index": 6,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 19,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "STATISTICS": {
                                      "id": 6089,
                                      "name": "modules.STATISTICS",
                                      "can_edit": null,
                                      "settings": null,
                                      "index": 8,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 29,
                                      "app_id": 1,
                                      "groups": null
                                  },
                                  "RUNNING_SUBMISSIONS": {
                                      "id": 6090,
                                      "name": "modules.RUNNING_SUBMISSIONS",
                                      "can_edit": 0,
                                      "settings": "municipalitySettings",
                                      "index": 2,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 15,
                                      "app_id": 1,
                                      "groups": null
                                  }
                              },
                              "main": {
                                  "id": 1,
                                  "name": "splitandmerge.SPLITEMARGELABEL",
                                  "icon": "images/splitIcon.png",
                                  "color": "473268",
                                  "href": "/gisnew/#/submissions/split-merge",
                                  "url": "split-merge",
                                  "translate": null,
                                  "translate_ar_caption": "خدمات الفرز الإلكتروني",
                                  "translate_en_caption": "1",
                                  "max_request_no": 500,
                                  "workflows": null,
                                  "apps_modules": null,
                                  "groups": null,
                                  "groups_permissions": null,
                                  "purpose": null,
                                  "show_in_dashboard": true,
                                  "can_search_inquiry": false
                              }
                          }
                      },
                      {
                          "id": 6082,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 43,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 43,
                              "name": "modules.UNPAYED_SUBMISSIONS",
                              "can_edit": 0,
                              "settings": "municipalitySettings",
                              "index": 5,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6083,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 42,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 42,
                              "name": "modules.PAYED_SUBMISSIONS",
                              "can_edit": 0,
                              "settings": "municipalitySettings",
                              "index": 5,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6084,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 16,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 16,
                              "name": "modules.RETURNED_SUBMISSION",
                              "can_edit": 0,
                              "settings": null,
                              "index": 3,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6085,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 35,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 35,
                              "name": "modules.SPLIT_STATISTICS",
                              "can_edit": null,
                              "settings": null,
                              "index": null,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6086,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 30,
                          "app_id": 12,
                          "apps_modules": {
                              "id": 30,
                              "name": "modules.PORTAL.POLL",
                              "can_edit": 0,
                              "settings": null,
                              "index": 17,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 12,
                              "name": "splitandmerge.portal",
                              "icon": "images/access.png",
                              "color": null,
                              "href": null,
                              "url": null,
                              "translate": null,
                              "translate_ar_caption": null,
                              "translate_en_caption": null,
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": false,
                              "can_search_inquiry": false,
                              "modules": {
                                  "PORTAL": {
                                      "POLL": {
                                          "id": 6086,
                                          "name": "modules.PORTAL.POLL",
                                          "can_edit": 0,
                                          "settings": null,
                                          "index": 17,
                                          "css_class": null,
                                          "applications": null,
                                          "create": null,
                                          "update": null,
                                          "delete": null,
                                          "get": 1,
                                          "group_id": 1830,
                                          "module_id": 30,
                                          "app_id": 12,
                                          "groups": null
                                      }
                                  }
                              }
                          }
                      },
                      {
                          "id": 6087,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 27,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 27,
                              "name": "modules.RATING",
                              "can_edit": null,
                              "settings": null,
                              "index": 7,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6088,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 19,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 19,
                              "name": "modules.ARCHIVED_SUBMISSION",
                              "can_edit": 0,
                              "settings": null,
                              "index": 6,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6089,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 29,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 29,
                              "name": "modules.STATISTICS",
                              "can_edit": null,
                              "settings": null,
                              "index": 8,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6090,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 15,
                          "app_id": 1,
                          "apps_modules": {
                              "id": 15,
                              "name": "modules.RUNNING_SUBMISSIONS",
                              "can_edit": 0,
                              "settings": "municipalitySettings",
                              "index": 2,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 1,
                              "name": "splitandmerge.SPLITEMARGELABEL",
                              "icon": "images/splitIcon.png",
                              "color": "473268",
                              "href": "/gisnew/#/submissions/split-merge",
                              "url": "split-merge",
                              "translate": null,
                              "translate_ar_caption": "خدمات الفرز الإلكتروني",
                              "translate_en_caption": "1",
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6091,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 25,
                          "app_id": 2,
                          "apps_modules": {
                              "id": 25,
                              "name": "modules.DEFAULT",
                              "can_edit": null,
                              "settings": null,
                              "index": 0,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 2,
                              "name": "splitandmerge.BUILDINGLICENSELABEL",
                              "icon": "images/building%20license.png",
                              "color": null,
                              "href": null,
                              "url": null,
                              "translate": null,
                              "translate_ar_caption": null,
                              "translate_en_caption": null,
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": false,
                              "can_search_inquiry": false,
                              "modules": {
                                  "DEFAULT": {
                                      "id": 6091,
                                      "name": "modules.DEFAULT",
                                      "can_edit": null,
                                      "settings": null,
                                      "index": 0,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 25,
                                      "app_id": 2,
                                      "groups": null
                                  }
                              }
                          }
                      },
                      {
                          "id": 6092,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 25,
                          "app_id": 4,
                          "apps_modules": {
                              "id": 25,
                              "name": "modules.DEFAULT",
                              "can_edit": null,
                              "settings": null,
                              "index": 0,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 4,
                              "name": "splitandmerge.VOCATIONALLICENCES",
                              "icon": "images/licence.png",
                              "color": null,
                              "href": null,
                              "url": null,
                              "translate": null,
                              "translate_ar_caption": null,
                              "translate_en_caption": null,
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": false,
                              "can_search_inquiry": false,
                              "modules": {
                                  "DEFAULT": {
                                      "id": 6092,
                                      "name": "modules.DEFAULT",
                                      "can_edit": null,
                                      "settings": null,
                                      "index": 0,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 25,
                                      "app_id": 4,
                                      "groups": null
                                  }
                              }
                          }
                      },
                      {
                          "id": 6093,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 23,
                          "app_id": 5,
                          "apps_modules": {
                              "id": 23,
                              "name": "modules.MAPVIEWER",
                              "can_edit": 0,
                              "settings": null,
                              "index": 1,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 5,
                              "name": "splitandmerge.MAPEXPLORER",
                              "icon": "images/egoExpIcon.png",
                              "color": "83561f",
                              "href": "/gisnew/#/maps",
                              "url": "maps",
                              "translate": null,
                              "translate_ar_caption": "المستكشف الجغرافي",
                              "translate_en_caption": null,
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": false,
                              "can_search_inquiry": false,
                              "modules": {
                                  "MAPVIEWER": {
                                      "id": 6093,
                                      "name": "modules.MAPVIEWER",
                                      "can_edit": 0,
                                      "settings": null,
                                      "index": 1,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 23,
                                      "app_id": 5,
                                      "groups": null
                                  },
                                  "APPLICATIONS": {
                                      "id": 3921,
                                      "name": "modules.APPLICATIONS",
                                      "can_edit": null,
                                      "settings": "applicationsSettings",
                                      "index": 14,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 2489,
                                      "module_id": 24,
                                      "app_id": 5,
                                      "groups": null
                                  }
                              },
                              "main": {
                                  "id": 5,
                                  "name": "splitandmerge.MAPEXPLORER",
                                  "icon": "images/egoExpIcon.png",
                                  "color": "83561f",
                                  "href": "/gisnew/#/maps",
                                  "url": "maps",
                                  "translate": null,
                                  "translate_ar_caption": "المستكشف الجغرافي",
                                  "translate_en_caption": null,
                                  "max_request_no": null,
                                  "workflows": null,
                                  "apps_modules": null,
                                  "groups": null,
                                  "groups_permissions": null,
                                  "purpose": null,
                                  "show_in_dashboard": false,
                                  "can_search_inquiry": false
                              }
                          }
                      },
                      {
                          "id": 6094,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 1830,
                          "module_id": 15,
                          "app_id": 7,
                          "apps_modules": {
                              "id": 15,
                              "name": "modules.RUNNING_SUBMISSIONS",
                              "can_edit": 0,
                              "settings": "municipalitySettings",
                              "index": 2,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 7,
                              "name": "splitandmerge.Enquires",
                              "icon": "images/enquiresIcon.png",
                              "color": null,
                              "href": "/gisnew/#/submissions/enquires",
                              "url": "enquires",
                              "translate": null,
                              "translate_ar_caption": "الإستفسارات",
                              "translate_en_caption": null,
                              "max_request_no": 500,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": false,
                              "can_search_inquiry": false,
                              "modules": {
                                  "RUNNING_SUBMISSIONS": {
                                      "id": 6094,
                                      "name": "modules.RUNNING_SUBMISSIONS",
                                      "can_edit": 0,
                                      "settings": "municipalitySettings",
                                      "index": 2,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 1830,
                                      "module_id": 15,
                                      "app_id": 7,
                                      "groups": null
                                  }
                              }
                          }
                      }
                  ],
                  "applications": null,
                  "users": null
              },
              {
                  "id": 2489,
                  "name": "استخراج البيانات",
                  "create_at": null,
                  "updateat": null,
                  "groups_permissions": [
                      {
                          "id": 3921,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 2489,
                          "module_id": 24,
                          "app_id": 5,
                          "apps_modules": {
                              "id": 24,
                              "name": "modules.APPLICATIONS",
                              "can_edit": null,
                              "settings": "applicationsSettings",
                              "index": 14,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 5,
                              "name": "splitandmerge.MAPEXPLORER",
                              "icon": "images/egoExpIcon.png",
                              "color": "83561f",
                              "href": "/gisnew/#/maps",
                              "url": "maps",
                              "translate": null,
                              "translate_ar_caption": "المستكشف الجغرافي",
                              "translate_en_caption": null,
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": false,
                              "can_search_inquiry": false
                          }
                      }
                  ],
                  "applications": null,
                  "users": null
              },
              {
                  "id": 5509,
                  "name": "مراجعين المرافق العامة",
                  "create_at": null,
                  "updateat": null,
                  "groups_permissions": [
                      {
                          "id": 6027,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 5509,
                          "module_id": 19,
                          "app_id": 19,
                          "apps_modules": {
                              "id": 19,
                              "name": "modules.ARCHIVED_SUBMISSION",
                              "can_edit": 0,
                              "settings": null,
                              "index": 6,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 19,
                              "name": "splitandmerge.gisservices",
                              "icon": "images/publicUtlity.png",
                              "color": "1f8380",
                              "href": "/gisv2/#/submissions/gisservices?tk=",
                              "url": "/gisv2/#/submissions/gisservices?tk=",
                              "translate": null,
                              "translate_ar_caption": "تراخيص المشاريع الخدمية",
                              "translate_en_caption": "1",
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false,
                              "modules": {
                                  "ARCHIVED_SUBMISSION": {
                                      "id": 6027,
                                      "name": "modules.ARCHIVED_SUBMISSION",
                                      "can_edit": 0,
                                      "settings": null,
                                      "index": 6,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 5509,
                                      "module_id": 19,
                                      "app_id": 19,
                                      "groups": null
                                  },
                                  "RETURNED_SUBMISSION": {
                                      "id": 6028,
                                      "name": "modules.RETURNED_SUBMISSION",
                                      "can_edit": 0,
                                      "settings": null,
                                      "index": 3,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 5509,
                                      "module_id": 16,
                                      "app_id": 19,
                                      "groups": null
                                  },
                                  "RUNNING_SUBMISSIONS": {
                                      "id": 6029,
                                      "name": "modules.RUNNING_SUBMISSIONS",
                                      "can_edit": 0,
                                      "settings": "municipalitySettings",
                                      "index": 2,
                                      "css_class": null,
                                      "applications": null,
                                      "create": null,
                                      "update": null,
                                      "delete": null,
                                      "get": 1,
                                      "group_id": 5509,
                                      "module_id": 15,
                                      "app_id": 19,
                                      "groups": null
                                  }
                              },
                              "main": {
                                  "id": 19,
                                  "name": "splitandmerge.gisservices",
                                  "icon": "images/publicUtlity.png",
                                  "color": "1f8380",
                                  "href": "/gisv2/#/submissions/gisservices?tk=",
                                  "url": "/gisv2/#/submissions/gisservices?tk=",
                                  "translate": null,
                                  "translate_ar_caption": "تراخيص المشاريع الخدمية",
                                  "translate_en_caption": "1",
                                  "max_request_no": null,
                                  "workflows": null,
                                  "apps_modules": null,
                                  "groups": null,
                                  "groups_permissions": null,
                                  "purpose": null,
                                  "show_in_dashboard": true,
                                  "can_search_inquiry": false
                              }
                          }
                      },
                      {
                          "id": 6028,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 5509,
                          "module_id": 16,
                          "app_id": 19,
                          "apps_modules": {
                              "id": 16,
                              "name": "modules.RETURNED_SUBMISSION",
                              "can_edit": 0,
                              "settings": null,
                              "index": 3,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 19,
                              "name": "splitandmerge.gisservices",
                              "icon": "images/publicUtlity.png",
                              "color": "1f8380",
                              "href": "/gisv2/#/submissions/gisservices?tk=",
                              "url": "/gisv2/#/submissions/gisservices?tk=",
                              "translate": null,
                              "translate_ar_caption": "تراخيص المشاريع الخدمية",
                              "translate_en_caption": "1",
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      },
                      {
                          "id": 6029,
                          "create": null,
                          "update": null,
                          "delete": null,
                          "get": 1,
                          "group_id": 5509,
                          "module_id": 15,
                          "app_id": 19,
                          "apps_modules": {
                              "id": 15,
                              "name": "modules.RUNNING_SUBMISSIONS",
                              "can_edit": 0,
                              "settings": "municipalitySettings",
                              "index": 2,
                              "css_class": null,
                              "applications": null
                          },
                          "groups": null,
                          "applications": {
                              "id": 19,
                              "name": "splitandmerge.gisservices",
                              "icon": "images/publicUtlity.png",
                              "color": "1f8380",
                              "href": "/gisv2/#/submissions/gisservices?tk=",
                              "url": "/gisv2/#/submissions/gisservices?tk=",
                              "translate": null,
                              "translate_ar_caption": "تراخيص المشاريع الخدمية",
                              "translate_en_caption": "1",
                              "max_request_no": null,
                              "workflows": null,
                              "apps_modules": null,
                              "groups": null,
                              "groups_permissions": null,
                              "purpose": null,
                              "show_in_dashboard": true,
                              "can_search_inquiry": false
                          }
                      }
                  ],
                  "applications": null,
                  "users": null
              }
          ],
          "positions": null,
          "committees": null,
          "is_super_admin": null,
          "esriToken": "YbmiIJTXdRRvpiS4uVN2rWsqeWHI2r6noSdEhiRTtR0.",
          "app_sub_count": null,
          "deactivation_reason": null,
          "is_readonly": null
      },
      "currentDate": "1443-05-09",
      "checked": false,
      "commentStep": ""
  }
]