import { host } from "imports/config";
export default {
  label: "استكمال المرفقات",
  sections: {
    approvals: {
      label: "استكمال المرفقات",
      fields: {
        electricity_approval: {
          label: "موافقة شركة الكهرباء",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          required: true,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        water_minister_approval: {
          label: "موافقة وزارة البيئة والمياة والزراعة",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          required: true,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        stc_approval: {
          label: "موافقة شركة الإتصالات السعودية",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          required: true,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        mobily_approval: {
          label: "موافقة شركة موبايلي",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          required: true,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        zain_approval: {
          label: "موافقة شركة زين",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          required: true,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
        balady_approval: {
          label: "موافقة المجلس البلدي",
          field: "simpleUploader",
          uploadUrl: `${host}/uploadMultifiles`,
          fileType: "image/*,.pdf",
          multiple: false,
          required: true,
          preRequest: (props) => {},
          postRequest: (uploadedUrl, props) => {},
        },
      },
    },
  },
};
