import { workFlowUrl } from "configFiles/config";

export const stepFields = [
  {
    name: "name",
    label: "Step name",
    required: true,
    uniqueWithUrl: {
      url: workFlowUrl + "/steps/uniqueName/",
      name_key: "key",
      value_key: "q",
    },
  },
  {
    name: "assign_to_position_id",
    moduleName: "positions",
    label: "Position",
    field: "select",
    label_key: "name",
    value_key: "id",
    fetch: `${workFlowUrl}/api/position`,
    conditionalNotRequired: ["assign_to_creator", "assign_to_group_id"],
  },
  {
    name: "assign_to_group_id",
    moduleName: "groups",
    label: "Group",
    field: "select",
    label_key: "name",
    value_key: "id",
    fetch: `${workFlowUrl}/api/group`,
    conditionalNotRequired: ["assign_to_creator", "assign_to_position_id"],
  },
  {
    name: "assign_to_creator",
    label: "Assign to creator",
    field: "boolean",
    type: "boolean",
    conditionalNotRequired: ["assign_to_group_id", "assign_to_position_id"],
    resetFields: ["assign_to_owner"],
  },
  {
    name: "assign_to_owner",
    label: "Assign to owner",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
    resetFields: ["assign_to_creator"],
  },
  {
    name: "is_create",
    label: "Is create step",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
  },
  {
    name: "setCreator",
    label: "Set creator",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
    permission: { show_every: ["is_create"] },
  },
  {
    name: "module_id",
    moduleName: "modules_id",
    label: "Module",
    field: "select",
    label_key: "name",
    value_key: "id",
    fetch: `${workFlowUrl}/api/modules`,
    required: true,
  },
  {
    name: "steps_actions",
    moduleName: "steps_actions",
    label: "Steps actions",
    field: "multiSelect",
    type: "object",
    label_key: "name",
    value_key: "name",
    fetch: `${workFlowUrl}/api/actions`,
  },
  {
    name: "group_id",
    moduleName: "groups",
    label: "Group assign",
    field: "select",
    label_key: "name",
    value_key: "id",
    required: "true",
    permission: {
      show_include_value_array: {
        steps_actions: [
          "global.ASSIGN",
          "global.ASSIGNMULTI",
          "global.TRANSFER",
        ],
      },
    },
  },
  {
    name: "saved_data",
    moduleName: "saved_data",
    label: "Saved data",
    field: "multiSelect",
    label_key: "name",
    value_key: "value",
    permission: {
      show_include_value_array: {
        steps_actions: [
          "global.APPROVE",
          "global.FINISH",
          "global.SUBMIT",
          "global.APPROVE",
        ],
      },
    },
    fetch: `${workFlowUrl}/api/savedata`,
  },
  {
    name: "validate_data",
    moduleName: "validate_data",
    label: "Validate data",
    field: "multiSelect",
    label_key: "name",
    value_key: "value",
    permission: {
      show_include_value_array: {
        steps_actions: [
          "global.APPROVE",
          "global.FINISH",
          "global.SUBMIT",
          "global.APPROVE",
        ],
      },
    },
    fetch: `${workFlowUrl}/api/validatedata`,
  },
  {
    name: "is_edit",
    label: "Can comment",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
  },
  {
    name: "is_optional",
    label: "Is optional",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
  },
  {
    name: "can_warn",
    label: "Can warn",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
  },
  {
    name: "is_deactivated",
    label: "Is deactivated",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
  },
  {
    name: "generate_export_no",
    label: "Generate export number",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
    permission: {
      show_include_value_array: {
        steps_actions: ["global.APPROVE", "global.APPROVE"],
      },
    },
  },
  {
    name: "scalation",
    label: "Has a time limit",
    field: "boolean",
    hideLabel: true,
    type: "boolean",
  },
  {
    name: "scalation_hours",
    label: "Scalation hours",
    type: "number",
    required: true,
    permission: { show_every: ["scalation"] },
  },
  {
    name: "scalator_positon_id",
    moduleName: "positions",
    label: "Scalator position",
    field: "select",
    label_key: "name",
    value_key: "id",
    permission: { show_every: ["scalation"] },
    conditionalNotRequired: ["scalator_group_id"],
  },
  {
    name: "scalator_group_id",
    moduleName: "groups",
    label: "Scalator group",
    field: "select",
    label_key: "name",
    value_key: "id",
    permission: { show_every: ["scalation"] },
    conditionalNotRequired: ["scalator_positon_id"],
  },
  {
    name: "show_step_in_list",
    label: "Show in lists",
    field: "boolean",
    type: "boolean",
  },
];
