export const ar = {
  login: {
    SESSIONENDED: "لقد انتهى الوقت المتاح",
    LOGINWELCOMELABEL: "مرحبا",
    LOGINFIRSTVALIDATIONMESSAGE: "أدخل اسم المستخدم وكلمة المرور",
    LOGINUSERNAMEPLACEHOLDER: "اسم المستخدم",
    LOGINPASSWORDPLACEHOLDER: "كلمة المرور",
    LOGINBUTTONLABEL: "دخول",
    LOGINREMEMBERMELABEL: "تذكرني",
    AMANAEMP: "مستخدم أمانة",
    LOGINFORGETPASSWORDLABEL: "نسيت كلمة المرور",
    LOGINERRORMESSAGEFOR3TIMES: "لقد وصلت لثلاث محاوت خطاْ في الدخول",
    LOGINERRORMESSAGE: "يوجد خطأ بكلمة المرور",
    LOGINERRORNOTEXISTMESSAGE: "المستخدم غير مسجل",
    UNACTIVEMSG: "برجاء تفعيل الحساب",
    UNACTIVEMSGREASON: " تم تجميد الحساب بسبب ",
    UNACTIVEMSGREASON2: "برجاء التواصل مع قسم الدعم الفنى",
    ACTIVETITLE: "تنشيط الحساب",
    CODEPLACEHOLDER: "كود التنشيط",
    ACTIVEBTN: "تنشيط",
    ACTIVATIONDONETITLE: "تم التنشيط",
    ACTIVATIONDONeMSG: "تم تفعيل الحساب بنجاح",
    ENTERSYSTEM: "الدخول للنظام",
    RESENDCODE: "إعاده أرسال الكود",
    UNAUTHORIZEDMSG: "اسم المستخدم غير موجود",
    UNREGISTER: "هذا المستخدم غير مسجل",
    REPEATAGAIN: "أعد المحاوله بعد 15 دقيقة",
    ACTIVATIONFAILD: "حدث خطأ أثناء تفعيل الحساب يرجى التواصل مع الدعم الفنى",
    ACTIVATIONSENTSUCCESS: "تم إرسال كود التفعيل",
    ACTIVATIONFAILSSEND: "فشل في إرسال التفعيل",
    MAILSENTSUCCESS: "تم الأرسال",
    MAILSENDFAILD: "خطأ أثناء الأرسال",
    ERRORONLOGIN: "حدث خطأ في الدخول",
    REQUIREDLOGINUSERNAME: "من فضلك أدخل اسم المستخدم",
    REQUIREDLOGINPASSWORD: "من فضلك أدخل كلمة المرور",
    USER_IS_ACTIV: "المستخدم مفعل",
    COMBINATION_ERROR_CODE: "تأكد من إدخال اسم المستخدم وكود التفعيل بشكل صحيح",
    COMBINATION_ERROR_LOGIN:
      "تأكد من إدخال اسم المستخدم وكلمه المرور بشكل صحيح",
    STOPPED_USER_MSG:
      "برجاء التواصل مع الدعم الفني للأمانة لتنشيط الحساب gis@eamana.gov.sa",
    NOT_SESSION_USER_ERROR: "المستخدم المدخل ليس نفس مستخدم الفترة السابقه",
    USERNAME_PASSWORD_REQUIRED: "من فضلك أدخل اسم المستخدم و الرقم السرى",
    LOGINCHANGEPASSWORDLABEL: "تغيير كلمة المرور",
    NEWPASSWORDLBL: "كلمة المرور الجديدة",
    NEWPASSWORDPLACEHOLDER: "ادحل كلمة المرور الجديدة",
    INVALIDNEWPASSWORD:
      "يجب أن تحتوي كلمة المرور الجديدة على (ثمانية أحرف على الأقل ، وحرف واحد كبير على الأقل ، وحرف صغير واحد ، وحرف خاص واحد)",
    NEWPASSWORDREQUIRED: "يجب ادخال كلمة المرور الجديدة",
    CONFIRMPASSWORDLBL: "تأكيد كلمة المرور",
    CONFIRMPASSWORDPLACEHOLDER: "ادخل تأكيد كلمة المرور",
    INVALIDCONFIRMPASSWORD:
      "يجب أن تحتوي تأكيد كلمة المرور على (ثمانية أحرف على الأقل ، وحرف واحد كبير على الأقل ، وحرف صغير واحد ، وحرف خاص واحد)",
    NOTEQUALPASSWORDS: "كلمات المرور غير متطابقة",
    CONFIRMPASSWORDREQUIRED: "يجب ادخال تأكيد كلمة المرور",
    PASSWORDCHANGEDSUCCESS: "تم تغيير كلمة المرور بنجاح",
    PASSWORDCHANGEDDFAILD: "لم تتم تغيير كلمة المرور بنجاح",
  },
  common: {
    submissions: "خدمات الفرز",
    "Fields do not match": " كلمة المرور غير متطابقة",
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",
  },
  labels: {
    supervision_letter: "بيانات خطاب الإدارة العامة لإشراف",
    supervision_attachments: "بيانات مرحلة الإشراف",
    efada_municipality_statements: "إفادة البلدية",
    site_data_services: "خدمات الموقع",
    Sun: "الأحد",
    Mon: "الإثنين",
    Tue: "الثلاثاء",
    Wed: "الأربعاء",
    Thu: "الخميس",
    Fri: "الجمعة",
    Sat: "السبت",
    locationData: "بيانات المواقع",
    mapEditFeatures: "مراجعة بيانات المواقع",
    editUpdateCreate: "مراجعة بيانات المعاملة",
    selectEditingWorkFlow: "مراجعة مسار العمل",
    investType: "تحديد نوع الاستثمار",
    fees: "رسوم المخطط",
    fees_addedparcels: "بيانات الفاتورة",
    tabsSummary: "ملخص",
    ENGCOMP_ALERTS: "انذارات المكتب الهندسي",
    NORTH_EAST_DIRECTION: "الشمالي الشرقي",
    NORTH_WEST_DIRECTION: "الشمالي الغربي",
    SOUTH_EAST_DIRECTION: "الجنوبي الشرقي",
    SOUTH_WEST_DIRECTION: "الجنوبي الغربي",
    update_contract_submission_data: "الغرض من تحديث الصكوك",
    UPDATECONTRACTNEWDATA: "بيانات المعاملة",
    CONTRACTUPDATEOWNWEDATA: "تعديل بيانات المالك",
    CONTRACTUPDATEBOUNDRIESUPDATES:
      " تحديث الحدود (أطوال الحدود من الاتجات الاربعة مع بيان الجار).",
    CONTRACTUPDATEBOUNDRIESMODIFICATION: "تعديل أبعاد الحدود.",
    CONTRACTUPDATEAREAMODIFICATIONINC: "تعديل المساحة (زيادة).",
    CONTRACTUPDATEAREAMODIFICATIONDEC: "تعديل المساحة (بالنقصان).",
    CONTRACTUPDATELENGTHSUNITS: "تحديث مميز الأبعاد .",
    CONTRACTUPDATEDISTRECTNAME: "تحديث البيانات المكانية (اسم الحي).",
    CONTRACTUPDATEPLANENUMBER: "تحديث البيانات المكانية (رقم المخطط).",
    CONTRACTUPDATEBLOCK: "تحديث بيانات مكانية (البلك).",
    CONTRACTUPDATEPAPERCONTRACT: " تحديث صك ورقي .",
    CONTRACTUPDATETOONECONTRACT: " فرز أراضي متعددة بصك واحد .",
    CONTRACTUPDATEMARGECONTRACTS: "دمج صكوك أراضى متعددة",
    TITLEOFAPP: "تحديث الصكوك",
    DUKANTRANSACTIONTYPE: "نوع المعاملة (دكان)",
    "Utility Same Distance": "بعد أقرب محطة في نفس الإتجاه",
    "Utility Opposite Distance": "بعد أقرب محطة في الإتجاه المقابل",
    "Please enter the distance": "من فضلك ادخل المسافة",
    PARCELNAME: "رقم قطعة الأرض",
    DUPLIXNAME: "رقم الدوبلكس",
    LEGEND: "مفتاح المعاملات",
    TITLE: "التقييمات",
    OFFICE: "اسم المكتب",
    RATING: "عدد الانذارات",
    OPTIONS: "خيارات",
    RESETBUTTON: "مسح الانذارات",
    duplix_building_details: "تفاصيل المبنى",
    duplix_checktor: "التقرير الفني",
    BlockNo: "رقم البلك",
    sakValid: "التأكد من سريان مفعول الصك",
    owner_value: "بيانات المالك",
    sub_search_with: "البحث عن طريق",
    OWNERIDHEAD: "رقم الهوية",
    OWNERID: "بيانات المالك",
    OWNERNAMEHEAD: "اسم المالك",
    ENTITYCODE: "كود الجهة",
    COMMERCIALREGISTRATIONNO: "رقم السجل التجارى",
    sugLandData: "المقترحات",
    sugLandData_duplex: "الدوبلكسات المقترحة",
    sugLandData_parcel: "الأراضي المقترحة",
    ParcelImage: "بيانات الأرض",
    CHANGEPARCELLABEL:
      "وجود اختلاف بين استمارة التطبيق على الطبيعة وصك الملكية عن بيانات الخريطة",
    subdivisionName: "مجاورة",
    PARCELCOUNTERDRAGREV: "أرض رقم",
    DUPLIXCOUNTERDRAGREV: "دوبلكس رقم",
    REQUESTEMPLOYEE: "اسم الموظف المختص",
    // dd: "ملاحظات جله",
    EDITPARCELTITLE: "تعديل طول الضلع",
    EDITPARCELLENGTH: "طول الضلع",
    EDITPARCELLENGTHPLACHHOLDER: "من فضلك أدخل أدخل طول الضلع",
    SELECTMOAMLATYPEOPTION: "إختر نوع المعاملة",
    DivisionNo: "مركز الحي",
    SubName: "اسم التقسيم",
    About: "عبارة عن",
    INVALID_OWNER_MOBILE: "من فضلك تأكد من أن رقم الجوال الخاص بالمالك صحيح",
    bda2l: "بدائل ضوابط تخطيط الأراضي",
    lagna_karar: "قرار اللجنة",
    print_takreer: "طباعة التقارير",
    selectedPlan: "المخطط المختار",
    REJECTION_AND_RETURN_ACTION: "الاعتذار عن المخطط المقترح حيث يلزم تعديله",
    ACCEPTANCE_ACTION: "موافقة اللجنة الفنية وفق ما ورد من بيانات المخططات",
    SakValid: "تأكد من سريان مفعول الصك",
    msa7yData: "بيانات الرفع المساحي",
    data_msa7y: "بيانات الرفع المساحي",
    mun_remark_1: "مخاطبة إدارة المساحة ",
    mun_remark_2: "مخاطبة البلدية المختصة ",

    data_msa7y1: "الأراضي المقترحة",
    data_msa7y2: "الدوبلكسات المقترحة",
    // landData: "بيانات الموقع",
    "Submission parcel area": "المساحة",
    "Submission parcels": "أراضي المعاملة",
    "Download CAD": "تحميل ملف الكاد",
    "CAD File": "ملف الكاد",
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",

    sellingConfirmation: "مرئيات رئيس البلدية / المساحة ",
    sellingConfirmation_2: "مرئيات التخطيط",
    requests: "المتطلبات النظامية",
    sellingConfirmation_3: "مرئيات الاراضى و الممتلكات",
    ApprovalGis_2: " اعتماد مدير عام التخطيط العمراني",
    ApprovalGis_3: "اعتماد وكيل الأمين المساعد للتخطيط العمراني",
    ApprovalGis_1: " اعتماد مدير إدارة ضبط التنمية",
    checkWords:
      " يقر مقدم الطلب بصحة جميع البيانات و اطلاعى على اتفاقية مستوى الخدمة",
    Map: "الخريطه",
    "Medical Ministry Approval": "موافقة وزارة الصحة",
    "School Ministry Approval": "موافقة وزارة التعليم",
    "Agri Ministry Approval": "موافقة وزارة الزراعة",
    "Trans Ministry Approval":
      "موافقة وزارة النقل علي ملائمة الموقع وعلاقته بالطريق العام",
    "Print Setting": "اعدادات الطباعة",
    printSetting: "اعدادات الطباعة",
    "Print Letter": "دباجة الخطاب",
    "Verified    Not Verified": "مطابق   |  غير  مطابق",
    conditions: "الاشتراطات",
    Conditions: "الاشتراطات",
    LandWithCoordinate: "بيانات الارض",
    buy_zayda: "استمارة شراء زائدة",
    suggestParcel: "موقع الزائدة",
    radio1: "مدى ملائمة تلك الزائدة",
    buyzayda: "بيانات شراء زائده",
    "Please Select Road Type": "من فضلك اختر نوع الطريق",
    "Please Select Utility Sub Type": "من فضلك اختر فئة المحطة",
    serviceSubmissionType: "بيانات المعاملة",
    "Please Select Utility Type": "من فضلك اختر نوع الخدمة",
    Admission: "التعهدات",
    Admissions: "البدائل",
    tabtiriPlans_attachments: "مرفقات المخطط التبتيري",
    "Step Name": "اسم الخطوة",
    admission: "التعهدات",
    "Utility Position": "موقع المحطة",
    "Road Type": "نوع الطريق",
    "Wedding Type": "الافراح",
    "Road Name": "اسم الطريق",
    "You Exceed Floor Area": "لقد تخطيت مساحة الطابق",
    "Road Mark": "العلامة الكيلومترية",
    "School Type": "نوع المدرسة",
    "Submission Conditions": "الاشتراطات",
    "Condition Data": "التحقق من الاشتراطات",
    Verified: "مطابق",
    "School Name": "اسم المدرسة",
    "School Gender": "فئة المدرسة",
    "School Level": "المرحلة التعليمية",
    "Hospital Type": "نوع المباني الصحية",
    "Utility Type": "نوع الخدمة",
    "Utility Sub Type": "فئة المحطة",
    "Print Kroky": "طباعة الكروكي المساحي",
    "Plane Approval": "موافقة الطيران المدني",
    "Others Attachments": "مرفقات الجهات الاخري",
    "Others Name": "اسم الجهات الاخري",
    "Select Approvals": "تحديد المرفقات",
    Level: "مستوي",
    "Please Enter All Field": "من فضلك ادخل جميع البيانات",
    comment: "ملاحظات",
    Represent: "الوكالة",
    "Sak Valid": "التأكد من سريان مفعول الصك",
    Sak: "صك",
    Representer: "الوكيل",
    remark: "ملاحظات",
    Remark: "ملاحظات",
    remarks: "ملاحظات",
    eng_create_remark: "ملاحظات المكتب الهندسي",
    surv_remark: "مراجعة وتدقيق الطلب",
    Remarks: "الملاحظات",
    "Cannot Add This Floor Please Change Type":
      "لا يمكنك اضافة طابق اخر من هذا النوع",
    "Please Select Sak Issuer": "من فضلك اختر جهة اعتماد الصك",
    "Defence Letter Number": "رقم خطاب الدفاع المدني",
    "Defence Letter Date": "تاريخ خطاب الدفاع المدني",
    // "Service": "خدمات",
    "Are You Sure from Delete Item ?": "هل انت متاكد من الحذف ؟",
    Outside: "ملحق خارجي",
    approvals: "موافقات الجهات الخارجية",
    "Owner Represent Approval": "اقرار المواطن بالتفويض",
    "Code Building Approval": "اقرار كود البناء",
    "Engineering Supervision": "المكتب المشرف",
    "Supervision contact": "عقد الاشراف",
    "Final Plans": "المخططات النهائية",
    "Sak Issuer": "جهة اصدار الصك",
    "Sak Image": "صورة الصك",
    sakData: "بيانات الصكوك",
    // "comment": ""
    Approvals: "مرفقات المشروع",
    "Electric Approval": "موافقة الكهرباء",
    "Transimition Approval": "مراجعة الادارة العامة لهندسة النقل والمرور",
    "Military Approval": "موافقة الدفاع المدني",
    "Water Approval": "موافقة مصلحة المياة",
    Members: "الاعضاء",
    Amin: "الامين",
    "Amin Representer": "وكيل الامين للتعمير والمشاريع",
    "Representer Helper": "مساعد وكيل الامين للتعمير والمشاريع",
    "Project Manager": "مدير ادارة المشاريع الكبري",
    "Important Project Engineer": "مهندس مشاريع هامة",
    project_attachment: "المرفقات المطلوبة",
    comments: "ملاحظات",
    Saks: "الصكوك",
    "Add Sak": "اضافة صك",
    "Sak Number": "رقم الصك",
    "Sak Date": "تاريخ الصك",
    "Trade Number": "عدد الوحدات التجاري",
    "Trade Area": "مساحة الوحدات التجاري",
    "House Number": "عدد الوحدات السكني",
    "House Area": "مساحة الوحدات السكني",
    "Manage Number": "عدد الوحدات الاداري",
    "Manage Area": "مساحة الوحدات الاداري",
    "Flat Number": "رقم الوحدة",
    "Kroky Image": "مرفق الكروكى المساحى",
    "Not Avaliable": "غير متوفر",
    Owner: "المالك",
    submissionType: "بيانات المعاملة",
    building: "بيانات المباني",
    "Side Image": "صورة الواجهة",
    "Top Image": "صورة الموقع العام",
    "Top Image farz": "صورة فوتوغرافية للأرض",
    "Building Ratio": "نسبة البناء %",
    "In Active": "مجمدة",
    "Total Requestd Parking": "عدد المواقف المطلوبة",
    "Supply Area": " مساحة المرافق (م2)",
    "Profile Image": "صورة الهوية",
    Backward: "ارتداد",
    Forward: "بروز",
    East: "الشرق",
    West: "الغرب",
    South: "الجنوب",
    North: "الشمال",
    "Building Surround": "ارتدادات و بروز المبني",
    "Fence Length": "طول السور",
    Warch: "طول الوارش",
    "Warch Length": "طول الوارش",
    "Sak Data": "بيانات الصكوك",
    "Road Planning": "مخطط مناسيب الطرق",
    "Light Planning": "مخطط الإنارة",
    "Damage Planning": "مخطط شبكة تصريف السيول",
    "Water Planning": "مخطط شبكات تصريف المياه والصرف الصحي",
    "Electric Planning": "مخطط شبكة الكهرباء وتوزيع غرف الكهرباء",
    "Phone Planning": "مخطط شبكة الهاتف",
    "Tabtir Planning": "المخطط التبتيري",
    "Owner Office Approval": "اتفاقية المالك ومكتب اتنفيذ",
    "Owner SuperVisse Approval": "اتفاقية المالك ومكتب الاشراف",
    "Owner Approvals": "موافقات المالك",
    "Owner Commitement": "تعهد المالك بالتنفيذ",
    "Conditional Paper": "مستندات المشروع",
    "Project Folder": "الرسومات الهندسية للمشروع (pdf)",
    "Project Files": "الرسومات الهندسية للمشروع (dwg)",
    "Viewing Images": "ملف اللقطات المنظورية للمعاملة",
    "Add Building": "إضافة مبني",
    "Add Floor": "إضافة طابق",
    "Add Flat": "إضافة وحدات الطابق",
    "Floor Type": "نوع الطابق",
    "Under Ground": "القبو",
    "Ground Attached": "ملحق أرض",
    Ground: "أرضي",
    Mezaneen: "ميزانين",
    Repeated: "متكرر",
    "Upper Attached": "ملحق علوي",
    Fence: "طول السور",
    Warsh: "طول الوارش",
    "Repeat Number": "عدد مرات تكرار الطابق",
    "Flat Name": "رقم الوحده",
    "Flat Usage": "استخدام الوحدة",
    House: "سكني",
    Trade: "تجاري",
    Service: "خدمة",
    Manage: "إداري",
    "Edit Flats": "وحدات الطابق",
    Park: "موقف",
    Flats: "وحدات الطابق",
    "Building Data": "بيانات المباني",
    // "Building Data": "",
    Building: "مبني",
    Buildings: "المباني",
    Using: "الاستخدام",
    Floors: "الطوابق",
    "Max Height": "أقصي ارتفاع للمبني (م)",
    "Total Area": "اجمالي مسطحات البناء (م2) ",
    "Total Parking": "عدد المواقف المؤمنة",
    applied: "تطبيق",
    "not applied": "بدون تطبيق",
    Parcels: "الاراضي",
    Gender: "النوع",
    Male: "ذكر",
    Female: "انثي",
    "Has Representer": "يوجد وكيل",
    "Representer Data": "بيانات الوكيل",
    "Represent Data": "بيانات الوكالة",
    "Add Representer": "اضافة وكيل",
    "Search Representer": "البحث عن وكيل",
    "Represent Sak Image": "صورة صك الوكالة",
    "Represent Sak Number": "رقم صك الوكالة",
    "Represent Sak Date": "تاريخ الإصدار",
    "Kroky Number": "رقم الكروكي",
    "Kroky Date": "تاريخ الكروكي",
    "Kroky Issue": "جهة اصدار الكروكي",
    "Kroky Data": "بيانات الكروكي المساحي",
    "Submission Data": "بيانات المعاملة",
    "Submission Type": "نوع المعاملة",
    "Submission Steps": "خطوات المعاملة",
    "Search With Kroky Number": "البحث برقم الكروكي",
    "Not attach To Kroky": "غير مرتبط بكروكي مساحي",
    "attach To Kroky": "مرتبط بكروكي مساحي",
    "Important Project": "مشاريع هامة",
    "Important Project Time": "مشاريع هامة بالتزامن",
    "Parcel Details": "بيانات الموقع",
    "East Length": "طول الحد الشرقي",
    "East Description": "وصف الحد الشرقي",
    "West Length": "طول الحد الغربي",
    "West Description": "وصف الحد الغربي",
    "South Length": "طول الحد الجنوبي",
    "South Description": "وصف الحد الجنوبي",
    "North Length": "طول الحد الشمالي",
    "North Width": "عرض الرصيف",
    "North Note": "وصف القسيمة للحد الشمالي",
    "South Width": "عرض الرصيف",
    "South Note": "وصف القسيمة للحد الجنوبي",
    "East Width": "عرض الرصيف",
    "East Note": "وصف القسيمة للحد الشرقي",
    "West Width": "عرض الرصيف",
    "West Note": "وصف القسيمة للحد الغربي",
    "North Description": "وصف الحد الشمالي",
    report: "طباعة",
    Person: "فرد",
    "owner type": "نوع المالك",
    Organization: "قطاع حكومي",
    Special: "قطاع خاص",
    Others: "أخري",
    "Add Owner": "اضافة مالك",
    "Add Mostafed": "اضافة مستفيد",
    "Nationaity Id Type": "نوع الهوية",
    "Please Select Nationaity Id Type": "من فضلك اختر نوع الهوية",
    "National ID": "رقم الهوية",
    "Nationality Id Issuer Name": "جهة اصدار الهوية",
    "Please Enter Nationality Id Issuer Name": "من فضلك اختر جهة اصدار الهوية",
    Nationality: "الجنسية",
    "Please Select Nationality": "من فضلك اختر الجنسية",
    "Delivery Post": "الرقم البريدي",
    "Please Enter Delivery Post": "من فضلك ادخل الرقم البريدي",
    "Please Enter Email": "من فضلك ادخل البريد الإلكتروني",
    File: "الملف",
    "Company Name": "اسم الجهة",
    "Please Enter Company Name": "من فضلك ادخل اسم الجهة",
    "Company Type": "نوع الجهة",
    "Commercial Registeration": "رقم السجل التجاري",
    "Please Enter Commercial Registeration": "من فضلك ادخل رقم السجل التجاري",
    WebSite: "الموقع الإلكتروني",
    "Please Enter WebSite": "من فضلك ادخل الموقع الإلكتروني",
    "Please Enter Mobile Number": "من فضلك ادخل رقم الجوال",
    "Please Enter Fax Number": "من فضلك ادخل رقم الفاكس",
    "Please Enter Address": "من فضلك ادخل العنوان",
    "Code Registeration": "كود الجهة",
    "Please Enter Code Registeration": "من فضلك ادخل كود الجهة",
    commercial_registeration: "رقم السجل التجاري",
    "Plan usages": "الاستخدامات",
    "Plan usage": "استخدام",
    "submission was found": "تم ايجاد بيانات المعاملة",
    "submission not found": "لا يوجد معاملة بالرقم المدخل",
    "Find submission": "البحث عن المعاملة",
    Sum: "المجموع",
    Total: "المجموع الكلي",
    OWNER: "المالك",
    PLAN: "التخطيط",
    plan_budget: "ميزانية المخطط",
    "Old submission attch": "المخطط القديم",
    Area: "مساحة (م2)",
    Usage: "الاستخدام",
    "Plan budget": "ميزانية المخطط",
    "Percentage type": "نوع النسب",
    "Area percentage %": "النسبة المئوية %",
    "Number of pieces": "عدد القطع",
    "Strategic use": "الاستعمال الاستراتيجي",
    "Link with surroundings": "الربط مع المجاوريين",
    "Plan name": "اسم المخطط",
    "Request number": "رقم المعاملة",
    "Warning Count": "عدد الإنذارات",
    HEAD_NAME: "اسم المكتب الهندسي",
    firstData: "البيانات الأساسية",
    "First data": "البيانات الأساسية",
    "One number": "الرقم الموحد",
    Credentials: "جهات الاعتماد",
    "Submission type": "نوع المعاملة",
    "no data found": "لا يوجد بيانات",
    "Final Approval Check": "خطابات الاعتماد",
    finalApprovalCheck: "خطابات الاعتماد",
    "Final drawing of Plan": "الرسم الهندسي النهائي للمخطط",
    "First drawing of Plan": "الرسم الهندسي الابتدائي للمخطط",
    "Submission Attach Date": "تاريخ نتيجة التقديم",
    "Government ID Number": "كود الجهة",
    "Company ID Number": "رقم السجل التجاري",
    "company ID Image": "صورة السجل التجاري",
    "Old Submission": "معاملة مؤرشفة",
    "Owner type": "نوع المالك",
    Individual: "فرد",
    Governmental: "جهة حكومية",
    "Company or institute": "مؤسسة أو شركة",
    Comments: "الملاحظات",
    "Fields do not match": " كلمة المرور غير متطابقة",
    password: "كلمة المرور",
    "New Password": "كلمة المرور الجديدة",
    "Confirm Password": "تاكيد كلمة المرور الجديدة",
    "Write your comments": "من فضلك ادخل تعليقك هنا ...",
    "please choose plan status": "  اختر حالة المخطط ",
    "Filter statistics by date": "بحث بالتاريخ",
    filter: "بحث",
    "File name": "حفظ باسم",
    from_date: " من تاريخ",
    to_date: "الى تاريخ",
    search_value: "كلمة البحث",
    search_with: "البحث عن طريق",
    status_search: "نوع البحث",
    "Reason for Stopping": "سبب التوقيف",
    PlanArchiving: "ارشفة المخططات",
    "No Data": "لا يوجد",
    summery: "الملخص",
    Summery: "الملخص",
    stoppingReason: "سبب التوقيف",

    firstApproval: "الاعتماد الأولي",
    "planApproval.submitapp.OWNER_APPROVAL":
      "طلب المالك أو الوكيل موقع ومصدق من المكتب",
    "planApproval.submitapp.REQUEST_APPROVAL":
      "تعهد من المالك بصحة البيانات مصدق من المكتب ",
    "planApproval.submitapp.KROKY_APPROVAL":
      "نسخة من الكروكي المساحي والرفع المساحي لموقع الأرض",
    "planApproval.submitapp.SOILSTUDY": "تقرير دراسة فحص التربة للموقع",
    "planApproval.submitapp.DEVAUTHOAPPROVEMENT":
      "تقرير الدراسة الهيدرولوجية للموقع",
    "planApproval.submitapp.PETROL_APPROVAL": "وزارة الطاقة",
    "planApproval.submitapp.AGGREE_COMMITTEE_APPROVAL":
      "موافقة وزارة الصناعة والثروة المعدنية",
    "planApproval.submitapp.INDUSTRY_CITY_APPROVAL": "",
    "planApproval.submitapp.ENVIROMENTAL_APPROVAL": "",
    firstApprovalNotes: "ملاحظات الاعتماد الأولي",
    approvalSubmissionNotes: " ملاحظات تقديم الطلب ",
    comments_approvalSubmissionNotes: " ملاحظات تقديم الطلب ",
    add_waseka: "وثيقة",
    dd: "ملاحظات جله",
    "Engineering License Number": "رقم الاعتماد المهنى ",
    "An error occured, can not retrieve data": "حدث خطأ اثناء استرجاع البيانات",
    Outbox: "الصادر",
    Outbox_Ordering: "التعميم الصادر",
    Inbox_Ordering: "التعميم الوارد",
    Inbox: "الوارد",
    Delayed: "المعاملات المتأخرة",
    Transferred: "المعاملات المحولة",
    Number: "الرقم",
    table_waseka: "وثيقة",
    Date: "التاريخ",
    Attachment: "المرفق",
    Subject: "موضوع الكروكي",
    Issuer: "جهة الإصدار",
    "First Approval": "الاعتماد الأولى",
    "Final Approval": "الاعتماد النهائى",
    finalApproval: "الاعتماد النهائى",
    finalApprovalNotes: "ملاحظات الاعتماد النهائى",
    "First Plan Number": "رقم المخطط الأولى",
    "Land Planning Committee Ruling Number": "رقم قرار لجنة تقسيمات الأراضى",
    "Land Planning Committee Ruling": "قرار لجنة تقسيمات الأراضى",
    "Ruling Year": "تاريخ القرار",
    Safar: "صفر",
    Muharram: "محرم",
    "Rabi' al-Awwal": "ربيع الأول",
    "Rabi' al-Thani": "ربيع الثانى",
    "Jumada al-Ula": "جمادى الأول",
    "Jumada al-Alkhirah": "جمادى الآخرة",
    Rajab: "رجب",
    "Sha’ban": "شعبان",
    Ramadhan: "رمضان",
    Shawwal: "شوال",
    "Thul-Qi’dah": "ذو القعدة",
    "Thul-Hijjah": "ذو الحجة",
    "Planning Studies": "الدراسات التخطيطية",
    pendingReview: "قيد المناقشة",
    pendingReviewNotes: "ملاحظات قيد المناقشة",
    notes: "ملاحظات",
    efadat: "الإفادات المدخلة",
    feesList: "فواتير المعاملة",
    notes11: "ملاحظات",
    notes12: "ملاحظات",
    notes13: "ملاحظات",
    notes14: "ملاحظات",
    notes15: "ملاحظات",
    planningStudies: "الدراسات التخطيطية",
    "Pending Review": "قيد المناقشة",
    "General Notes": "ملاحظات عامة",
    "Submission Number": "رقم التقديم",
    "Submission Date": "تاريخ التقديم",
    "Submission Attachment": "مرفق التقديم",
    "Submission Result": "نتيجة التقديم",
    "Technical Committee Names": "قائمة اسماء اللجنة الفنية",
    Contracts: "الصكوك",
    "Riyadh Development Authority Report": "قرار هيئة تطوير الارض",
    "Preview File": "معاينة الملف",
    "Delete File": "حذف الملف",
    "Remove File": "حذف الملف",
    Summary: "الملخص",
    "Select year": "اختر السنة",
    "Select month": "اختر الشهر",
    "Select day": "اختر اليوم",
    "Office Phone Number": "رقم هاتف المكتب",
    Attachments: "مرفقات",
    All_Attachments: "جميع المرفقات",
    sub_info: "معلومات عن المعاملة",
    plans: "المخططات المقترحة",
    tabtiriPlans: "المخطط التبتيري",
    //all_attachments: "جميع المرفقات",
    "Traffic Studies": "الدراسات المرورية",
    traffic_studies: "الدراسات المرورية",
    "Soil Testing": "فحص التربة",
    soil_testing: "فحص التربة",
    Studies: "دراسات",
    studies: "دراسات",
    "Hydraulics Studies": "دراسات الهيدرولجية",
    hydraulics_studies: "دراسات الهيدرولجية",
    "Letter Number": "رقم الخطاب",
    "Letter Date": "تاريخ الخطاب",
    Notes: "ملاحظات",
    "Letter Attachment": "ارفاق خطاب الاعتماد",
    "Ownership Data": "بيانات الملكية",
    ownership_data: "بيانات الملكية",
    "Property Contract": "صك الملكية",
    property_contract: "صك الملكية",
    "Contract Number": "رقم صك الوكالة",
    "Contract Date": "تاريخ الاصدار",
    "Contract Issuer": "جهة الاصدار",
    "Contract Image Attachment": "ارفاق صورة الصك",
    "Survey Report": "القرار المساحي",
    servey_report: "القرار المساحي",
    "Survey reports": "القرارات المساحية",
    survey_reports: "القرارات المساحية",
    survey_report: "القرار المساحى",
    "Report Number": "رقم القرار المساحى",
    "Report Date": "تاريخ القرار المساحى",
    "Survey Report Issuer": "جهة اصدار القرار",
    "Survey Report Image Attachment": "ارفاق صورة القرار المساحى",
    "Basic Data": "بيانات الاستشاري",
    basic_data: "بيانات الاستشاري",
    "File Number": "رقم الملف",
    Year: "السنة",
    "Consultant Name": "اسم الاستشارى",
    "Office Pohone Number": "رقم هاتف المكتب",
    "Fax Number": "رقم الفاكس",
    "Company Fax": "رقم الفاكس",
    "Please Enter Company Fax": "من فضلك ادخل رقم الفاكس",
    "Planning Engineer Phone Number": "رقم مهندس التخطيط",
    "Application Letter": "خطاب التقديم",
    "Consultant Authorization": "تفويض الاستشارى",
    "Land Data": "بيانات الأرض",
    "Destination Data": "بيانات الجهة المستفيدة",
    "judge_letter": "بيانات الحكم القضائي / الخطاب",
    "project_attachments": "اسم المشروع ومرفقاته",
    "Allotment Type": "نوع التخصيص",
    "allotment_type": "نوع التخصيص",
    destinationData: "بيانات الجهة المستفيدة",
    destinationData1: "بيانات الجهة الحكومية",
    letter: "بيانات الخطاب",
    attachments: "مرفقات",
    "suggest Parcel": "موقع الزائدة",
    "Service Range": "الاشتراطات",
    landData: "بيانات المعاملة",
    District: "الحى",
    Street: "الشارع",
    "Plan Number": "رقم المخطط",
    "Piece Number": "رقم القطعة",
    "Plan Area": " مساحة القطعة(م2)",
    "Urban Boundaries Phase": "مرحلة النطاق العمرانى",
    "District Location": "كروكى موقع الحى",
    "Plan Image": "كروكى المخطط",
    "Urban Boundaries Requirements": "اشتراطات النطاقات العمرانية",
    "Urban Boundary": "النطاق العمراني",
    "Land Usage": "استعمال الارض (نوع المخطط)",
    "Land Location": "موقع الارض",
    "Owner Data": "بيانات المالك",
    mostafed: "إضافة مالك",
    // mostafed: "بيانات المستفيد",
    ownerData: "بيانات المالك",
    waseka: "وثيقة الملكية",
    submission_data_export: "بيانات طلب ارشفة الصادر والوارد",
    submission_data: "بيانات معاملة الكروكى",
    "Owner Name": "اسم المالك",
    "Department Name": "اسم الإدارة",
    "National ID Number": "رقم الهوية",
    "National ID Image": "صورة الهوية",
    "Search in column": "البحث فى",
    "Number of Steps": "عدد الخطوات",
    "Translation file": "ملف الترجمة",
    "Issue multiple requests on land": "إصدار أكثر من معاملة على الأرض",
    "Validate selected lands": "التحقق من الأراضى المختارة",
    State: "الحالة",
    Active: "مفعلة",
    "Not active": "مجمدة",
    Company: "شركة",
    Corporation: "مؤسسة",
    "ِActive Company": "مفعلة",
    "InActive Company": "مجمدة",
    "Workflow Principal": "مسئول مسار العمل",
    Workflows: "مسارات العمل",
    "Contracts Credence": "اصدار الصكوك",
    "Electrical Credence": "إصدار موافقات كهرباء",
    "Water Credence": "إصدار موافقات مياه",
    "Procuration Credence": "إصدار وكالات",
    Website: "الموقع الإلكتروني",
    "Issuer Code": "كود الجهة",
    "Issuer type": "نوع جهة الاصدار",
    Fax: "فاكس",
    "Committe Members": "اعضاء اللجنة الفنية",
    "National ID Type": "نوع الهوية",
    Application: "التطبيق",
    Read: "قراءة",
    Create: "انشاء",
    Update: "تعديل",
    Delete: "حذف",
    "Group Name": "اسم المجموعة",
    "Maximum Number of Requests": "عدد الطلبات المسموح بتقديمها",
    Status: "الحالة",
    Address: "العنوان",
    Department: "القسم",
    Municipality: "البلدية",
    "Phone Number": "رقم الهاتف",
    "Mobile Number": "رقم الجوال",
    "Email Address": "البريد الإلكتروني",
    "User Type": "نوع المستخدم",
    Province: "الأمانة",
    "Engineering Company": "المكتب الهندسى",
    Name: "الاسم",
    Age: "السن",
    Email: "البريد الإلكترونى",
    Type: "نوع المعاملة",
    search: "بحث",
    create: "معاملة جديدة",
    create_ordering: "تعميم جديد",
    Username: "اسم المستخدم",
    Password: "كلمة المرور",
    Home: "الرئيسية",
    "Contact us": "اتصل بنا",
    Applications: "التطبيقات",
    application: "تطبيق",
    Committies: "اللجان الفنية",
    committee: "لجنة فنية",
    Committee: "اللجنة فنية",
    "Print File": "طباعة ملف",
    Departments: "الاقسام",
    department: "قسم",
    "Engineering Companies": "المكاتب الهندسية",
    "engineering company": "مكتب هندسي",
    Groups: "المجموعات",
    group: "مجموعة",
    Issuers: "جهات الاصدار",
    issuer: "جهة اصدار",
    "Issuers Types": "انواع جهات الاصدار",
    "issuer type": "جهة اصدار",
    "National ID Types": "انواع الهوية",
    "national ID type": "نوع هوية",
    Nationalities: "الجنسيات",
    nationality: "جنسية",
    Municipalities: "البلديات",
    Districts: "الأحياء",
    district: "حي",
    UrbanBoundries: "النطاقات العمرانية",
    UrbanBoundry: "النطاق العمراني",
    LandUsages: "استعملات الأرض (نوع المخطط)",
    LandUsage: "استعمال الأرض (نوع المخطط)",
    municipality: "بلدية",
    News: "الاخبار",
    news: "خبر",
    Owners: "الملاك",
    owner: "مالك",
    Positions: "المسميات الوظيفية",
    position: "مسمى وظيفى",
    Questions: "الاسئلة",
    question: "سؤال",
    "User Owners": "المستفيدين",
    "user owner": "مستفيد",
    "User Titles": "المستخدمين",
    "user title": "مستخدم",
    "Workflow Titles": "مسارات العمل",
    "workflow title": "مسار العمل",
    ADMIN: "ادارة النظام",
    Administration: "ادارة النظام",
    ContractUpdate: " تحديث الصكوك",
    EngCompanyApproval: "اعتماد المكاتب الهندسية",
    Enquires: "استفسارات",
    SPLITEMARGELABEL: "خدمات الفرز",
    SURVEYREPORT: "اصدار الكروكي المساحى",
    // "ordering": "الش",
    BUILDINGLICENSELABEL: "رخص البناء",
    PLANSAPPROVALLABEL: "اعتماد المخطاطات",
    // "VOCATIONALLICENCES": "Vocational Licences",
    MAPEXPLORER: "المستكشف الجغرافى",
    UpdateMap: "تحديث رخص الاساس",
    // "planApproval": "Contracts updates",,
    ENG_COMP_FREEZE: "المكاتب الهندسية", //almakateb al handasya
    "modules.ENG_COMP_FREEZE": "المكاتب الهندسية", //almakateb al handasya
    APPLICATIONS: "التطبيقات", //el tatbe2at
    "modules.APPLICATIONS": "التطبيقات", //el tatbe2at
    ARCHIVED_SUBMISSION: "الارشيف", //al arshef
    ADDEDPARCELS_REQUESTED_REPORTING: "تقارير معاملات الزوائد التنظيمية",
    "modules.ADDEDPARCELS_REQUESTED_REPORTING":
      "تقارير معاملات الزوائد التنظيمية",

    E3TMAD_REQUESTED_REPORTING: "تقارير معاملات الإعنماد",
    "modules.E3TMAD_REQUESTED_REPORTING": "تقارير معاملات الإعنماد",
    Finished: "المعاملات المنتهية", //al arshef
    "modules.ARCHIVED_SUBMISSION": "الارشيف", //al arshef
    CAD_EXPORT: "اصدار ملف الكاد", //esdar malaf el cad
    "modules.CAD_EXPORT": "اصدار ملف الكاد", //esdar malaf el cad
    COMMITTEES: "اللجان الفنية", //al lgan al fanya
    "modules.COMMITTEES": "اللجان الفنية", //al lgan al fanya
    CREATE_REQUEST: "تقديم الطلب", //ta2dem el talb
    "modules.CREATE_REQUEST": "تقديم الطلب", //ta2dem el talb
    CREATE_ORDERING: "تقديم تعميم", //ta2dem tameem
    "modules.CREATE_ORDERING": "تقديم تعميم", //ta2dem tameem
    DEFAULT: "الرئيسية", //el ra2esya
    "modules.DEFAULT": "الرئيسية", //el ra2esya
    DEPARTMENTS: "الاقسام", //al aqsam
    "modules.DEPARTMENTS": "الاقسام", //al aqsam
    DRAFT_SUBMISSIONS: "معاملات تحت التجهيز", //mo3amlat ta7t el taghez
    "modules.DRAFT_SUBMISSIONS": "معاملات تحت التجهيز", //mo3amlat ta7t el taghez
    ENGINEERING_COMPANIES: "المكاتب الهندسية المعتمدة", //al mkateb el handasya el mo3tamda
    "modules.ENGINEERING_COMPANIES": "المكاتب الهندسية المعتمدة", //al mkateb el handasya el mo3tamda
    "modules.PLANUSAGES": "الاستخدامات",
    GROUPS: "المجموعات", //al magmo3at
    "modules.GROUPS": "المجموعات", //al magmo3at
    ISSUERS_TYPE: "انواع جهات الاصدار", //anwa3 gehat al tawseq
    "modules.ISSUERS_TYPE": "انواع جهات الاصدار", //anwa3 gehat al tawseq
    ISSUERS: "جهات الاصدار",
    "modules.ISSUERS": "جهات الاصدار",
    MAPVIEWER: "المستكشف الجغرافى", //al mostakshef el go3"rafy
    "modules.MAPVIEWER": "المستكشف الجغرافى", //al mostakshef el go3"rafy
    MUNICIPALITIES: "البلديات", //al baladyat
    "modules.MUNICIPALITIES": "البلديات", //al baladyat
    NATIONALIDTYPES: "انواع الهويات", //anwa3 al hawya
    "modules.NATIONALIDTYPES": "انواع الهويات", //anwa3 al hawya
    NATIONALITIES: "الجنسيات", //al gensyat
    "modules.NATIONALITIES": "الجنسيات", //al gensyat
    NEWS: "الاخبار", //al akhbar
    "modules.NEWS": "الاخبار", //al akhbar
    OWNERS: "الملاك", // al molak
    "modules.OWNERS": "الملاك", // al molak
    "PORTAL.POLL": "تقييمات البوابة", //taqymat el bawabta
    "modules.PORTAL.POLL": "تقييمات البوابة", //taqymat el bawabta
    POSITIONS: "المسمى الوظيفى", //al mosama al wazefy
    "modules.POSITIONS": "المسمى الوظيفى", //al mosama al wazefy
    QUESTIONS: "الاسئلة", //al as2ela
    "modules.QUESTIONS": "الاسئلة", //al as2ela
    RATING: "التقييمات", //al taqyemat
    "modules.RATING": "التقييمات", //al taqyemat
    REJECTED_SUBMISSION: "المعتذر عنها", //al mo3tazr 3anha
    "modules.REJECTED_SUBMISSION": "المعتذر عنها", //al mo3tazr 3anha
    REQUESTED_SUBMISSION: "الصادر", //al sader
    "modules.REQUESTED_SUBMISSION": "الصادر", //al sader
    REQUESTED_ORDERING: "التعميم الصادر", //ordering al sader
    "modules.REQUESTED_ORDERING": "التعميم الصادر", //ordering al sader
    RETURNED_SUBMISSION: "المعادة", //al mo3ada
    "modules.RETURNED_SUBMISSION": "المعادة", //al mo3ada
    RUNNING_SUBMISSIONS: "الوارد", //al wared
    "modules.RUNNING_SUBMISSIONS": "الوارد", //al wared
    RUNNING_ORDERING: "التعميم الوارد", //ordering al wared
    "modules.RUNNING_ORDERING": "التعميم الوارد", //ordering al wared
    SCALATION: "المتأخرة", //al mot25era
    "modules.SCALATION": "المتأخرة", //al mot25era
    STATISTICS: "الاحصائيات", //al e7sa2yat
    "modules.STATISTICS": "الاحصائيات", //al e7sa2yat
    USER_TITLE: "المستخدمين", //al most5admen
    "modules.USER_TITLE": "المستخدمين", //al most5admen
    WORKFLOW_TITLE: "مسارات العمل", //masarat el 3aml
    "modules.WORKFLOW_TITLE": "مسارات العمل", //masarat el 3aml
    // "APPROVAL":"",
    SUB_MUNICIPILTY: "البلديات الفرعية", //al baladayat al far3ya
    "modules.SUB_MUNICIPILTY": "البلديات الفرعية", //al baladayat al far3ya
    SPLIT_STATISTICS: "احصائيات الفرز", //e7sa2yat al farz
    "modules.SPLIT_STATISTICS": "احصائيات الفرز", //e7sa2yat al farz
    Finished: "المنتهية", //al montahya
    "modules.FINISH_SUBMISSION": "المنتهية", //al montahya
    ENGCOM_STATISTICS: "احصائيات المكتب الهندسى", //e7sa2yat al mkateb el handasya
    "modules.ENGCOM_STATISTICS": "احصائيات المكتب الهندسى", //e7sa2yat al mkateb el handasya
    REVIEW_REQUESTS: "طلبات الاعتماد", //talbat el e3tmad
    "modules.REVIEW_REQUESTS": "طلبات الاعتماد", //talbat el e3tmad
    "modules.STOPPED_SUBMISSION": "المعاملات المتوقفة",
    STOPPED_SUBMISSION: "المعاملات المتوقفة",
    "modules.DISTRICTS": "الأحياء",
    Transferred: "المعاملات المحولة",
    DISTRICTS: "الأحياء",
    "modules.URBANBOUNDRY": "النطاقات العمرانية",
    URBANBOUNDRY: "النطاقات العمرانية",
    "modules.LANDUSAGE": "استعملات الأرض (نوع المخطط)",
    LANDUSAGE: "استعملات الأرض (نوع المخطط)",
    // "MAP_OBJECT_ID_IDENTIFICATION":""
    "global.ASSIGN": "توجيه",
    "global.ASSIGNMULTI": " توجيه لمتعدد",
    "global.REJECT": "اعتذار",
    "global.SUBMIT": "ارسال",
    "global.SIGN": "موافقة",
    "global.SENDAMANA": "ارسال للأمانة",
    "global.RETURN": "اعادة توجيه",
    "global.RETURNFROMSTART": "إعادة توجيه مع إعادة المسار",
    "global.GOTO": "مخاطبة",
    "global.TRANSFER": "إحالة إلي",
    "global.BACK": "إنهاء المخاطبة",
    "global.APPROVE": "موافقه و توجيه الى",
    "global.FINISH": "انهاء",
    "global.STOP": "ايقاف",
    "Export number": "رقم الصادر",
    "Export date": "تاريخ الاصدار",
    Note: "ملاحظة",
    "Step name": "اسم الخطوة",
    Position: "ممثل الخطوة (المسمى الوظيفى)",
    Group: "ممثل الخطوة (المجموعة)",
    "Assign to creator": "توجيه الى المنشىء",
    "Assign to owner": "توجيه الى المالك",
    "Is create step": "خطوة أنشاء",
    "Set creator": "ضبط المُنشأ",
    Module: "المحتوى",
    "Steps actions": "الأجراءات",
    "Group assign": "ممثل إجراء التوجيه",
    "Saved data": "حفظ البيانات",
    "Validate data": "تحقيق بيانات",
    "Can comment": "إمكانيه التعليق",
    "Is optional": "خطوة إختيارية",
    "Can warn": "امكانيه التحذير",
    "Is deactivated": " خطوة غير مفعلة",
    "Generate export number": "أصدار رقم اصدار",
    "Has a time limit": "لها مدة زمنية",
    "Scalation hours": "المدة الزمنية لأجراء الخطوة",
    "Scalator position": "ممثل التصعيد(المسمى الوظيفى)",
    "Scalator group": "ممثل الخطوة (المجموعة)",
    "Show in lists": " إظهار الخطوة في القوائم",
    "Message text": "الرسالة",
    "Send to owner": "إرسال للمالك",
    "Send to actor": "إرسال للمنفذ",
    "Send to creator": "إرسال للمنشىء",
    Actions: "الأجراءات",
    Yes: "نعم",
    No: "لا",
    time: "الوقت",
    PlanStatus: "قرار اللجنة الفنية",
    PARCEL_PLAN_NO: "رقم المخطط",
    eng_name: "اسم الاستشاري",
    owner_ssn: "رقم هوية المالك",
    owner_name: "اسم المالك",
    request_no: "رقم المعاملة",
    file_no: "رقم الملف",
    "Under going": "تحت الاجراء",
    "First approval": "معتمد أولي",
    "Final approval": "معتمد نهائي",
    Approval: "بيانات التعميم",
    Stopped: "موقف",
    Rejected: "مرفوض",
    "Search with": "نوع البحث",
    "search value": "بحث",
    "From date": "من تاريخ",
    "To date": "إلى تاريخ",
    "Status search": "حالة المخطط",
    Search: "بحث",
    "Search with id": "البحث برقم الهوية",
    "Remove file": "حذف الملف",
    Statistics: "الإحصائيات",
    investment_Statistics: "مؤشرات",
    investment_Indicators: "مؤشرات الاستثمار",
    FollowingRequests: " متابعة المعاملات",
    "Illustration of all transactions": "رسم توضيحي لأنواع معاملات (*)",
    "Illustration of transactions types": "رسم توضيحي لمراحل المعاملة ",
    steps: "الخطوات",
    runningProcesses: "معاملات جارية",
    totalProcesses: "إجمالي المعاملات",
    canceledProcesses: "معاملات مرفوضة",
    rejectedProcesses: "معاملات معتذر عنها",
    finishedProcesses: "معاملات منتهية",
    stoppedProcesses: "معاملات متوقفة",
    finalApprovalProcesses: "معاملات الاعتماد النهائي",
    firstApprovalProcesses: "معاملات الاعتماد الأولي",
    underGoingProcesses: "معاملات تحت الاجراء",
    "Processes kind": "أنواع المعاملات",
    "Number of processes": "	عدد المعاملات",
    "Municipality name": "البلدية",
    // sellingConfirmation: "مرئيات رئيس البلدية / المساحة ",
    // sellingConfirmation_1: "مرئيات التخطيط",
    // sellingConfirmation_2: "مرئيات الاراضى و الممتلكات",
    krar_amin: "قرار معالى الامين",
    ma7dar: "محضر تقدير",
    ma7dar_lagna_number: "رقم محضر اللجنة الفنية",
    ma7dar_lagna_date: "تاريخ محضر اللجنة الفنية",
    print_notes: "ملاحظات الطباعة",
    lagna_notes: "ملاحظات اللجنة الفنية",
    date: "التاريخ",
    karar_amin_date: "",
    debagh: "",
    land_bound: "",
    owner_approval: "موافقة المالك",
    khetab: "خطاب العدل",
    printCreate: "ملاحظات طباعة الطلب",
    processes: "",
  },
  actions: {
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",
    Flats: "وحدات الطابق",
    "successfuly added": "تمت الاضافة بنجاح",
    "failed to add": "حدث خطأ",
    "successfuly edited": "تم التعديل بنجاح",
    "failed to edit": "فشل التعديل",
    "successfully deleted": "تم الحذف بنجاح",
    "failed to delete": "فشل الحذف",
    "unable to delete urban boundry because there are submissions using it":
      "لا يمكن الحذف لأن هناك مشاريع تستعملها",
    "unable to delete group because there are users that belongs to it":
      "لا يمكن حذف المجموعة لأن هناك مستخدمين ينتمون إليها",
    "unable to delete user because he belongs to groups":
      "لا يمكن حذف هذا المستخدم لأنه ينتمي لمجموعة",
    Sum: "المجموع",
    "Username doesn't exist": "يرجى التأكد من اسم المستخدم",
    "Wrong password": "يرجى التأكد من كلمة المرور ",
    "Are you sure you want to delete this item?":
      "هل انت متاكد انك تريد حذف هذا العنصر؟",
    "Sign out": "تسجيل الخروج",
    "Sign in": "تسجيل الدخول",
    Close: "اغلاق",
    Save: " حفظ",
    Cancel: "إغلاق",
    Add: "اضافة",
    Next: "التالى",
    Previous: "السابق",
    Submit: "حفظ",
    Enter: "دخول",
    Edit: "تعديل",
    Accept: "قبول",
    Delete: "حذف",
    Yes: "نعم",
    No: "لا",
    Zoom: "تكبير",
    ZoomIn: "تكبير الخريطة",
    ZoomOut: "تصغير الخريطة",
    Pan: "تحريك الخريطة",
    editBoundries: "تعديل طول و عرض الخريطة",
    DownloadCAD: "تحميل ملف الكاد",
    Actions: "اجراءات",
    "Change Password": "تعديل كلمة المرور",
    Freeze: "تجميد",
    Activate: "تفعيل",
    "global.ASSIGN": "توجيه",
    "global.ASSIGNMULTI": " توجيه لمتعدد",
    "global.REJECT": "اعتذار",
    "global.SUBMIT": "ارسال",
    "global.SIGN": "موافقة",
    "global.SENDAMANA": "ارسال للأمانة",
    "global.RETURN": "اعادة توجيه",
    "global.RETURNFROMSTART": "إعادة توجيه مع إعادة المسار",
    "global.GOTO": "مخاطبة",
    "global.TRANSFER": "إحالة إلي",
    "global.BACK": "إنهاء المخاطبة",
    "global.APPROVE": "موافقه و توجيه الى",
    "global.FINISH": "انهاء",
    "global.STOP": "ايقاف",
    Continue: "إستكمال المعاملة",
    Alert: "انذار",
    Print: "طباعة",
    InvoicePrint: "طباعة الفاتورة",
    "Save edits": "حفظ التعديلات",
    "Continue submission": "استكمال المعاملة",
    "Save draft": " حفظ مؤقت",
    "Send SMS": "ارسال رسالة",
    Search: "بحث",
    Clear: "ازالة",
    "Successfully retrieved data": "تم استرجاع البيانات بنجاح",
    "Succesfully deleted": "تم الحذف بنجاح",
    "Succesfully transfered": "تم التحويل بنجاح",
    "Succesfully freezed": " تم تجميد المكتب بنجاح ",
    "Succesfully activated": "تم تفعيل المكتب بنجاح ",
    "An error occured, can not retrieve data": "حدث خطأ اثناء استرجاع البيانات",
    "Failed to delete": "حدث خطأ",
    "Fields do not match": " كلمة المرور غير متطابقة",
    "modules.ENG_COMP_FREEZE": "المكاتب الهندسية", //almakateb al handasya
    "modules.APPLICATIONS": "التطبيقات", //el tatbe2at
    "modules.ARCHIVED_SUBMISSION": "الارشيف", //al arshef
    "modules.ADDEDPARCELS_REQUESTED_REPORTING":
      "تقارير معاملات الزوائد التنظيمية",
    "modules.E3TMAD_REQUESTED_REPORTING": "تقارير معاملات الإعنماد",
    "modules.CAD_EXPORT": "اصدار ملف الكاد", //esdar malaf el cad
    "modules.COMMITTEES": "اللجان الفنية", //al lgan al fanya
    "modules.CREATE_REQUEST": "تقديم الطلب", //ta2dem el talb
    "modules.CREATE_ORDERING": "تقديم تعميم", //ta2dem tameem
    "modules.DEFAULT": "الرئيسية", //el ra2esya
    "modules.DEPARTMENTS": "الاقسام", //al aqsam
    "modules.DRAFT_SUBMISSIONS": "معاملات تحت التجهيز", //mo3amlat ta7t el taghez
    "modules.ENGINEERING_COMPANIES": "المكاتب الهندسية المعتمدة", //al mkateb el handasya el mo3tamda
    "modules.GROUPS": "المجموعات", //al magmo3at
    "modules.ISSUERS_TYPE": "انواع جهات الاصدار", //anwa3 gehat al tawseq
    "modules.ISSUERS": "جهات الاصدار",
    "modules.MAPVIEWER": "المستكشف الجغرافى", //al mostakshef el go3"rafy
    "modules.MUNICIPALITIES": "البلديات", //al baladyat
    "modules.NATIONALIDTYPES": "انواع الهويات", //anwa3 al hawya
    "modules.NATIONALITIES": "الجنسيات", //al gensyat
    "modules.NEWS": "الاخبار", //al akhbar
    "modules.OWNERS": "الملاك", // al molak
    "modules.PORTAL.POLL": "تقييمات البوابة", //taqymat el bawabta
    "modules.POSITIONS": "المسمى الوظيفى", //al mosama al wazefy
    "modules.QUESTIONS": "الاسئلة", //al as2ela
    "modules.RATING": "التقييمات", //al taqyemat
    "modules.REJECTED_SUBMISSION": "المعتذر عنها", //al mo3tazr 3anha
    "modules.REQUESTED_SUBMISSION": "الصادر", //al sader
    "modules.REQUESTED_ORDERING": "التعميم الصادر", //ordering al sader
    "modules.RETURNED_SUBMISSION": "المعادة", //al mo3ada
    "modules.RUNNING_SUBMISSIONS": "الوارد", //al wared
    "modules.RUNNING_ORDERING": "التعميم الوارد", //ordering al wared
    "modules.SCALATION": "المتأخرة", //al mot25era
    "modules.STATISTICS": "الاحصائيات", //al e7sa2yat
    "modules.USER_TITLE": "المستخدمين", //al most5admen
    "modules.WORKFLOW_TITLE": "مسارات العمل", //masarat el 3aml
    "modules.SUB_MUNICIPILTY": "البلديات الفرعية", //al baladayat al far3ya
    "modules.SPLIT_STATISTICS": "احصائيات الفرز", //e7sa2yat al farz
    "modules.FINISH_SUBMISSION": "المنتهية", //al montahya
    "modules.ENGCOM_STATISTICS": "احصائيات المكتب الهندسى", //e7sa2yat al mkateb el handasya
    "modules.REVIEW_REQUESTS": "طلبات الاعتماد", //talbat el e3tmad
    "modules.STOPPED_SUBMISSION": "المعاملات المتوقفة",
    "modules.DISTRICTS": "الأحياء",
    "modules.URBANBOUNDRY": "النطاقات العمرانية",
    "modules.LANDUSAGE": "استعملات الأرض (نوع المخطط)",
    "modules.PLANUSAGES": "الاستخدامات",
  },
  cadData: {
    DUPLIXSPLITEDERRORMESSAGE:
      "لا يمكنك أختيار فلل منفصلة لان طول أقل ضلع فى هذه الدوبلكس أقل من 11.5 متر",
    DUPLIXMARGEDERRORMESSAGE:
      "لا يمكنك أختيار فلل متصلة لان طول أقل ضلع فى هذه الدوبلكس أقل من 9.5 متر",
    BUILDINGDETAILSREQUIRVALIDATION: "من فضلك أدخل تفاصيل المبني",
    "mapview.parcels.NOTIFY": "هذة الأرض خارج حدود الأراضي المختارة",
    "mapview.parcels.APPART_NOTIFY": "هذا المبني خارج حدود الأرض المختارة",
    "mapview.parcels.APPART_NOTIFY_INTERSECT":
      "هذا المبني يتقاطع مع الأرض المختارة",
    "mapview.parcels.NOTIFY_INTERSECT":
      "هذة الأرض تتقاطع مع احد الأراضي المختارة",
    FarzNotifyDuplix: "لابد من إدخال اكثر من دوبلكس لأنها معاملة فرز",
    "mapview.parcels.DamgNotify":
      "لابد من إدخال أرض واحدة فقط لأنها معاملة دمج",
    "mapview.parcels.FarzNotify": "لابد من إدخال اكثر من أرض لأنها معاملة فرز",
    "mapview.parcels.AreaNotify":
      "مساحة الأراضي المختارة لا تساوي مساحة الأراضي المقترحة",
    FLOORVALIDATION: "ملف الكاد لا يحتوى على طبقة الدور",
    DETAILSVALIDATION: "ملف الكاد لا يحتوى على طبقة التفاصيل",
    PARCELSVALIDATION: "ملف الكاد لا يحتوى على طبقة الاراضي",
    ARCVALIDATION: "هذا الملف يحتوى على خط من نوع ارك وهذا غير مدعوم",
    perfectCad: "المخطط المقترح الأول",
    secondCad: "المخطط المقترح الثاني",
    thirdCad: "المخطط المقترح الثالث",
    NOTVALIDCAD: "أوتوكاد غير مطابق للمواصفات",
    BOUNDRYNOTFOUND: "طبقة الحدود غير موجودة",
    HASSAMESPATIALID: "هذة الأرض تتماثل مع أحد الأراضي المختارة",
    PLANOOUTSIDETHEBOUDRY: "المخطط خارج حدود المخطط المقترح",
    MSGFOREQUALTYOFAREAS:
      "يجب ان تكون مساحة الأرض وأطوال الحدود من الصك مساوية لمساحة الأرض وأطوال الحدود من الرفع المساحى",
    DIFFRENT_MUN_CHOOSE:
      "من فضلك تأكد من حدود الكاد المرفق داخل البلدية المختارة.",
    SOLID_REPORT_REQUIRED: "من فضلك ادخل تفاصيل تقرير التربة",
    MAX_WEIGHT_ERROR: "من فضلك ادخل الرقم اقل من 100",
    WEIGHT_MAX_100: "من فضلك تأكد من مجموع الأوزان المدخلة",
    INVALID_WEIGHT_REQUIRED: "من فضلك تأكد من ادخال التقييم ",

    THREEPLANSAREMANDATORY: "يجب اضافة المخططات الثلاث",
    INSERTONEPLANATLEAST: "يجب اضافة خطة اقتراحية واحدة على الأقل",
    COMPLETEPARCELDESCRIPTION: "من فضلك قم بإضافة مواصفات الأرض",
    PARCELCOUNTERDRAG: "أرض رقم ",
  },
  messages: {
    RIdRequestError: "برجاء مراجعة الدعم الفني لإصدار هوية عقارية",
    DeedAlreadyGenerated: "برجاء مراجعة الدعم الفني تم اصدار صك للمعاملة",
    momrahDeedRequestObjectError: "خطأ في بيانات الصك برجاء مراجعة الدعم الفني",
    momrahDeedRequestError: "خطأ في طلب الصك برجاء مراجعة الدعم الفني",
    "global.RIdRequestError": "برجاء مراجعة الدعم الفني لإصدار هوية عقارية",
    "global.RIDRequestIssued":
      "عذرا لا يمكن ارسال الطلب (يوجد طلب اصدار هوية عقارية)",
    "global.DeedRequestIssued": "عذرا لا يمكن ارسال الطلب (يوجد طلب اصدار صك)",
    "global.ElectronicDeedUpdateError":
      "برجاء مراجعة الدعم الفني لتحديث الصك الإلكتروني",
    "global.DeedAlreadyGenerated":
      "برجاء مراجعة الدعم الفني تم اصدار صك للمعاملة",
    "global.momrahDeedRequestObjectError":
      "خطأ في بيانات الصك برجاء مراجعة الدعم الفني",
    "global.momrahDeedRequestError": "خطأ في طلب الصك برجاء مراجعة الدعم الفني",

    IS_NOT_WITHIN_URBAN_AREA_BOUNDRY: "هذه الأرض خارج النطاق العمراني",
    SakExists: "تم ادخال الصكوك المختارة من قبل",
    "global.ownerExists": "تم ادخال الملف من قبل",
    NOT_EQUAL_PARCEL_NUMBER:
      "من فضلك تأكد من ان عدد الأراضي فى الرفع المساحي يساوي عدد الأراضي المختارة في بيانات الكروكي",
    UPDATE_BLOCK: "من فضلك قم بتغير احد البلوكات فى الأراضي",
    UPDATE_PLAN_NUMBER: "من فضلك قم بتغير احد ارقام المخططات فى الأراضي",
    UPDATE_DISTRICT_NAME: "من فضلك قم بتغير احد اسماء الأحياء فى الأراضي",
    MODIFY_AREA_DECREASE: "من فضلك قم بانقاص احد مساحات الأراضي",
    MODIFY_AREA_INCREASE: "من فضلك قم بزيادة احد مساحات الأراضي",
    SCALTION_MIN_NUM: "ادخل الأدنى لعدد ساعات المدة الزمنية ساعة واحدة",
    SCALTION_MAX_NUM: "ادخل الاقصى لعدد ساعات التأخير 100 ساعة",
    ASSIGN_SPECIFIC_VALIDATION: "من فضلك اختر المجموعة أوالوظيفة للتوجيه",
    SCALATION_CKKBOX: "لها مدة زمنية",
    SCALATION_ERROR_VALIDATION:
      "من فضلك اختر المجموعات أو المسمى الوظيفي فى حالة المدة الزمنية",
    GROUP_ASSIGN: "من فضلك اختر المسمى الوظيفي أو المجموعة",
    GROUPS_APPS_PRM: "من فضلك أدخل التطبيقات أو وظائف النظام",
    UNIQUE: "هذا الحقل موجود مسبقا",
    ISSUER_TYPE_CHECKBOX: "من فضلك اختر جهة إصدار",
    NO_DATA_MSG: "لا يوجد بيانات",
    PANDSERORRE: "هناك خطأ فى البنود",
    APPARTMENTSAREAS:
      "أجمإلى المساحات الاجمالية للوحدات العقارية لا تساوى أجمإلى مسطحات البناء",
    EXCEDFILES: "لقد تخطيت الأعداد المحدده",
    FLOOR_UNIQUE: "هذا الطابق مستخدم من قبل",
    CHOOSENFROMPORPUSES: "لابد الأختيار من الأغراض",
    PARCEL_UNIQUE_ALREADY: "أسماء الأراضى لابد ان تكون متشابهة",
    PARCEL_UNIQUE: "تم إدخال رقم الأرض من قبل تأكد من إدخال رقم أرض جديد",
    PARCEL_ALL_UNIQUE: "تم إدخال أرقام الأراضي من قبل",
    CONTRACT_ABSENCE: "لابد من وجود صك لكل أرض",
    WIZERD_SUBMIT_ERROR: "تأكد من إدخال المعامله بشكل صحيح",
    OWNERSMUSTMUDIFIED: "لابد من تعديل الملاك",
    COMMITIEACTORSLENGTHVALIDATION: "اللجنة الفنية لابد ان تكون فرد واحد",
    MODIFY_LENGTH_BOUNDRIES_CHECK: "لابد من تحديث أبعاد حدود أحد الأراضى",
    CHECKONEAREAVALIDATION200:
      "من فضلك أختر العلامه لتاكيد مساحة الدوبلكس بعد الفرز",
    MUSTSELECTALLLANDS: "لابد من أختيار جميع الاراضى للدخول فى الصك",
    MUSTRESETALLLANDS: "لابد من مسح الأراضي كلها لإعادة ادخالها",
    MUSTSELECTONELAND: "لابد من أختيار أرض واحدة للدخول فى الصك",
    MUSTDEFFRICESCONTRACTS: "لابد من أختلاف جميع أرقام الصكوك",
    MUSTENTERELECTRICROOMAREATEXT: "لابد من أدخال المساحة نصاً",
    MUSTENTERELECTRICROOMAREA: "لابد من أدخال مساحة غرفة الكهرباء",
    RESETFAIL: "Reset failed. Internal server error!",
    RESETSUCCESS: "تم مسح كل الانذارات بنجاح",
    CONFIRMRESET: "هل تريد بالتأكيد مسح كل الانذارات؟",
    MAX_SUBMISSIONS: "لقد تخطيت اعداد المعاملات المسموح بها",
    MAX_ENQUIRES: "لقد تخطيت اعداد الطلبات المسموح بها",
    BUILDINGCADDESCRIBTIONCONTEXT:
      "- يجب أن يتبع نظام الاحداثيات Projected WGS 1984-UTM 39 N. <br /> - يجب أن يكون ملفالاتوكاد بصيغة DWG. <br />- يتكون ملف الاتوكاد من مضلع مغلق (Closed Polyline) لكل مبنى. <br /> -" +
      "يجب أن يكون المبنى داخل حدود أرض موضوع المعاملة.",
    BUILDINGCADDESCRIBTIONTITLE: "مواصفات ملف الأتوكاد للمبانى",
    DOPLIXPARCELCADDESCRIBTIONCONTEXT:
      "- يجب أن يتبع نظام الاحداثيات Projected WGS 1984-UTM 39 N. <br /> - يجب أن يكون ملف الاتوكاد بصيغة DWG. <br />- يتكون ملف الاتوكاد من مضلع مغلق (Closed Polyline) لكل دوبلكس. <br /> -" +
      "يجب أن تكون مجموع مساحات الأراضى المقترحة تساوى مجموع مساحات الأراضى موضوع المعاملة",
    DUPLIXCADDESCRIBTIONTITLE: "مواصفات ملف الأتوكاد للدوبلكسات",
    PARCELCADDESCRIBTIONCONTEXT:
      "- يجب أن يتبع نظام الاحداثيات Projected WGS 1984-UTM 39 N. <br /> - يجب أن يكون ملف الاتوكاد بصيغة DWG. <br />- يتكون ملف الاتوكاد من مضلع مغلق (Closed Polyline) لكل أرض. <br /> -" +
      "يجب أن تكون مجموع مساحات الأراضى المقترحة تساوى مجموع مساحات الأراضى موضوع المعاملة ",
    PARCELCADDESCRIBTIONTITLE: "مواصفات ملف الأتوكاد للأراضى المقترحة",
    VAILDTYPSSUGGESTIONDUPLIXVALIDATIONMSG:
      "من فضلك راجع أنواع الدوبلكسات المدخلة",
    REQUIRNAMESUGGESTIONDUPLIXVALIDATIONMSG:
      " من فضلك أدخل اسماء الدوبلكسات وأنواعها",
    WRONGDUPLIXNAMESUGGESTIONVALIDATIONMSG:
      "من فضلك أدخل اسماء الدوبلكسات مختلفة",
    TITLEDUPLIXOFTABSIXACCONE: "الدوبلكسات المقترحة",
    PANDALLVALIDATIONMSG: "من فضلك تحقق من أدخال البيانات كاملة",
    CONTRACTSIMAGESVALIDATIONMSG: "من فضلك أدخل صور عقود الأراضي",
    APPATMENTREQUIRNAMESUGGESTIONVALIDATIONMSG:
      "من فضلك أدخل اسماء الوحدات العقارية",
    REQUIRNAMESUGGESTIONVALIDATIONMSG: "من فضلك أدخل اسماء الأراضى",
    WRONGAPPARTNAMESUGGESTIONVALIDATIONMSG:
      "من فضلك أدخل أرقام الوحدات العقارية مختلفة",
    WRONGSUGGESTIONVALIDATIONWITHLETTERSMSG:
      "من فضلك تاكد من توزيع الأراضي و إدخال الحدود بالأحرف",
    WRONGSUGGESTIONVALIDATIONMSG:
      "من فضلك تاكد من توزيع الأراضي و إدخال الحدود",
    CADREQUIRED: "من فضلك تاكد من ادخال ملف الرفع المساحي",
    WRONGSUGGESTIONVALIDATIONMSGDUPLIX:
      "من فضلك تاكد من توزيع الدوبلكسات و إدخال الحدود",
    REVIEWENGINEERINGOFFICE: "نأمل مراجعة التخطيط العمراني",
    PARCELSBOUNDIRESMSG: "من فضلك أدخل تفاصيل الحدود",
    RESET_CONFIRM:
      "هذا الاجراء سوف يقوم بالغاء ما بعده \n هل انت متأكد من حفظ البيانات ؟",
    WARN_CONFIRM: "هل تريد بالتأكيد انذار المكتب الهندسي؟",
    ERRORMSG:
      "لا يمكنك إنشاء معاملة على الأرض نظرا لعدم وجود صلاحية لهذا المكتب على هذا المخطط",
    PARCELSUBMISSIONDATAERROR:
      "حدود وأبعاد الأرض من الصك والرفع المساحى غير متساوية",
    AREANUMBERSWITHTEXT: "من فضلك أدخل المساحة نصاً هنا",
    PARCELSAREAERROR: "مساحات الاراضى من الصك والرفع المساحى غير متساوية",
    "global.VERFICATIONCODEERROR": "من فضلك تأكد من رمز التحقيق المدخل.",
    "global.forbidden": "غير مصرح لك بهذا الإجراء",
    SAVEDDRAFTUSED: "لم يتم الحفظ لأستخدام هذا الاسم مسبقا",
    MULTIERRORFILESIZE: "يوجد ملف حجمة أكبر من الحجم المطلوب",
    ERRORFILESIZE: "هذا الملف حجمة أكثر من الحجم المطلوب",
    "global.ERRORINWRITEFILE":
      "حدث خطأ عند كتابة الملف على الخادم يرجى التواصل مع الدعم الفنى",
    "global.INTERNALSERVERERROR":
      "حدث خطأ داخلى فى النظام يرجى التواصل مع الدعم الفنى.",
    Error: "حدث خطأ داخلى فى النظام يرجى التواصل مع الدعم الفنى.",
    "global.NoContent": "لا يوجد محتوى",
    "global.SUBMITREQUESTFAILD":
      "يوجد خطأ فى إرسال المعاملة يرجى التواصل مع الدعم الفنى",
    "global.UPDATINGfEATURESFAILED":
      "حدث خطأ أثناء تعديل البيانات الجغرافية ، برجاء مراجعة الدعم الفني",
    WEAK_PASSWORD:
      " الرجاء ادخال كلمة مرور معقدة تحتوى على حرف كبير حرف صغير وأرقام وعلامات خاصة وطول اكثر من 8 رموز",
    "global.CADERROR": "هذا الملف غير مطابق للمواصفات",
    SAVE_EDITS_DRAFT_MSG:
      "سيتم فقد بيانات المعامله القديمه هل انت متأكد من اتمام الحفظ؟",
    WRONG_EXTENSION: "هذا الملف غير مدرج ضمن الملفات المسموح اختيارها",
    NOT_VALID_CONTRACT: "الصك المدخل غير صالح من فضلك تاكد من معلومات الصك",
    ENDED_CONTRACT: "الصك المدخل منتهي من فضلك تاكد من معلومات الصك",
    MSGERROR_CONFIRM_PASS: "كلمه المرور غير متطابقه مع التأكيد",
    SAK_REQUIRE: "من فضلك تأكد من إدخال جميع الصكوك للأراضي",
    "global.PARCELSWARNING":
      "لا يمكن إنشاء معاملة علي هذة الأرض لانها مرتبطة بمعاملة جارية",
    DUPLIXSPLITEDERRORMESSAGE:
      "لا يمكنك أختيار فلل منفصلة لان طول أقل ضلع فى هذه الدوبلكس أقل من 11.5 متر",
    DUPLIXMARGEDERRORMESSAGE:
      "لا يمكنك أختيار فلل متصلة لان طول أقل ضلع فى هذه الدوبلكس أقل من 9.5 متر",
    DUPLIX_MERGE_SPLITE:
      "لابد من أختيار أما فلل منفصلة أو متصلة حتى يسمح المرور الى الخطوة التالية",
    PARCEL_AREA_PROBLEM:
      "تحقق من مجموع المساحات الموجوده فى الوضع المقترح والمعتمد",
    DUPLIX_UNIQUE: "تم إدخال رقم الدوبلكس من قبل تأكد من إدخال رقم جديد",
    DUPLIX_ERROR_MSG: "لا يمكنك أضافة هذه الدوبلكس , تأكد من أطوال الأضلاع",
    DUPLIX_ERROR_MSG_EDIT:
      "لا يمكنك تعديل هذه الدوبلكس , تأكد من أطوال الأضلاع",
    APPART_UNIQUE: "هذه الشقة مدخلة من قبل",
    wrongFarz:
      "عذرا، لإستكمال فرز الأراضي لابد أن يكون الملف يحتوي على أكثر من قطعة أرض",
    wrongDamge:
      "عذرا، لإستكمال دمج الأراضي لابد أن يكون الملف يحتوي على قطعة أرض واحدة",
    required: "يجب اضافة أرض",
    ParcelArea: "يجب ادخال حقل المساحة لكل من الأراضي المدخلة",
    allowedArea: "نأمل مراجعة التخطيط العمراني",
    validboundries: "من فضلك أدخل تفاصيل الحدود",
    USINGSYMBOLCHECKERS: "تحقق من نوع رمز الأستخدام",
    errorInParcelData:
      "من فضلك أدخل المساحة ورموز الاستخدام و وصف الأستخدام لكل ارض",
    wrongFarzOneParcel: "لا يمكن تقديم معاملة فرز أراضي لنوع فرز لأكثر من أرض",
    validRequestTypes: "لا يمكن تقديم معاملة فرز أراضي لنوع دمج لأرض واحدة",
    PARCELDESCRIPTIONANDBOUNDARIES: "من فضلك أدخل مواصفات وحدود الأرض",
    WRONGNAMESUGGESTIONVALIDATIONMSG: "من فضلك أدخل اسماء الاراضى مختلفة",
    requirNameSuggest: "من فضلك أدخل اسماء الأراضى",
    MSGFOREQUALTYOFAREAS:
      "يجب ان تكون مساحة الأرض وأطوال الحدود من الصك مساوية لمساحة الأرض وأطوال الحدود من الرفع المساحى",
    validTypeSuggest: "من فضلك راجع أنواع الدوبلكسات المدخلة",
    MUSTDEFBETWEENAREAANDCUTTS:
      "لابد أن تكون مجموع مساحات ااشطفات وغرف الكهرباء أقل من مساحة الاأرض",
    VALIDREQUEST: "يجب عليك إدخال أكثر من قطعة أرض لهذة المعاملة",
    PARCELDETAILS: "من فضلك أدخل المساحة ورموز الاستخدام لكل ارض",
    KROKYDETAILSVALIDATION: "من فضلك أدخل حدود أبعاد المعاملة",
    PARCEL_SYMBOL_ERROR: "تاكد من رموز الاستخدام سكنى / ترفيهى",
    DUPLIX_SYMBOL_ERROR: "تاكد من رموز الاستخدام صالحه لفرز الدوبليكسات",
    DRAFT_EDIT_REQUEST_SUCCESS: "تم الحفظ بنجاح",
    DRAFT_EDIT_REQUEST_ERROR:
      "حدث خطأ اثناء حفظ المعاملة من فضلك اعد المحاولة مرة اخرى او يرجى التواصل مع الدعم الفنى",
    "Please Select Attachment": "من فضلك اختر احد المرفقات",
    "Please Choose 3 members": "من فضلك اختر ثلاث اعضاء اللجنة",
    "Please Sure You Enter All Grounds":
      "من فضلك تاكد من ادخال جميع الادوار الارضية",
    "Please Sure You Enter All Flats": "من فضلك تاكد من ادخال جميع الوحدات",
    "Name already exists": "هذا الاسم مستعمل مسبقا",
    "Step name already exists": "هذا الاسم مستعمل مسبقا",
    "National ID already exists":
      "رقم الهوية مسجل من قبل برجاء ادخال رقم الهوية فى خانة البحث برقم الهوية",
    "Commercial Registeration already exists":
      "رقم السجل التجاري مسجل من قبل برجاء ادخال رقم السجل التجاري فى خانة البحث برقم السجل التجاري",
    "Code Registeration already exists":
      "كود الجهة مسجل من قبل برجاء ادخال كود الجهة فى خانة البحث بكود الجهة",
    "These studies are not filled yet ": "هذه الدراسات لم تملأ بعد  : ",
    hydraulics_studies: "دراسات الهيدرولجية",
    soil_testing: "فحص التربة",
    traffic_studies: "الدراسات المرورية",
    "the table is required to be filled": "يجب ملأ الجدول",
    "Studies are not filled yet": "برجاء العلم انه لم يتم ادخال الدراسات",
    "Are you sure you want to delete this item?":
      "هل انت متاكد انك تريد حذف هذا العنصر؟",
    "Are you sure you want to freeze this account?":
      "هل انت متاكد من تجميد هذا الحساب؟",
    "Are you sure you want to activate this account?":
      "هل انت متاكد من تفعيل هذا الحساب؟",
    Required: "مطلوب",
    "Required {{label}}": "من فضلك ادخل {{label}}",
    "RequiredCheck {{label}}": "من فضلك اختر {{label}}",
    "No data": "لا يوجد بيانات",
    "Invalid username or password": "خطأ في اسم المستخدم أو كلمة المرور",
    "Are you sure you want to delete this": "هل انت متاكد انك تريد حذف",
    "?": "؟",
    "Successfully updated": "تم التعديل بنجاح",
    "global.PARCELSWARNINGAPPROVED":
      "لا يمكن إنشاء معاملة علي هذه الأرض . يرجي مخاطبة الأمانة",
    "global.ParcelAllocatedError":
      "عذرا، لا يمكن إنشاء طلبكم تم تخصيص هذه الأرض من قبل",
    "global.PARCELSWARNING":
      "لا يمكن إنشاء معاملة علي هذه الأرض لانها مرتبطة بمعاملة جارية",
    "global.ERRORINSERVICE":
      "برجاء التواصل مع قسم الدعم الفنى لتقنية الاتصالات الادارية",
    "global.SIGNATUREERROR":
      "لا يمكن ارسال هذه المعاملة لعدم اكتمال جميع التواقيع",
    "global.ERRORINFEES":
      "برجاء التواصل مع قسم الدعم الفنى لتشغيل حاسبة الرسوم",
    "global.ERRORINSADAD": "برجاء التواصل مع قسم الدعم الفنى لتشغيل خدمة سداد",
    "Failed to update": "حدث خطأ",
    "Successfully created draft": "تم الحفظ بنجاح",
    "used draft": "هذا الاسم مستخدم مسبقا",
    "Successfully created": "تمت الاضافة بنجاح",
    "Invalid file type": "نوع الملف غير صالح",
    "Successfully retrieved data": "تم استرجاع البيانات بنجاح",

    "An error occured, can not retrieve data": "حدث خطأ اثناء استرجاع البيانات",
    "Are you sure?": "هل أنت متأكد؟",
    "Successfully global.APPROVE request with number ":
      "تم الموافقة على المعاملة بنجاح برقم",
    "Successfully global.SUBMIT request with number ":
      "تم  حفظ وارسال المعاملة بنجاح برقم",
    "Successfully global.ASSIGN request with number ":
      "تم  حفظ وارسال المعاملة بنجاح برقم",
    "Successfully global.RETURN request with number ":
      "تم إعادة توجيه المعاملة بنجاح برقم",
    "Successfully global.RETURNFROMSTART request with number ":
      "تم إعادة توجيه المعاملة بنجاح برقم",
    "Successfully global.REJECT request with number ": "تم رفض المعاملة رقم",
    "Successfully global.STOP request with number ": " تم ايقاف المعاملة رقم",
    "Successfully global.FINISH request with number ": " تم انهاء المعاملة رقم",
    "Successfully global.SENDAMANA request with number ":
      "تم ارسال المعاملة بنجاح رقم",
    "Successfully sent": "تم الارسال بنجاح",
    "Successfully approved": "تم الموافقة",
    "failed to send": "حدث خطأ",
    "Failed to create draft": "حدث خطأ",
    "Successfully saved": "تم الحفظ بنجاح",
    "failed to save": "لم يتم الحفظ",
    "set draft name": "حفظ",
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",
  },
  tabs: {
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",
    "Request No": "رقم المعاملة",
    problemReason: "سبب المشكلة",
    "Step Name": "اسم الخطوة",
    Charger: "مسئول الخطوة",
    "Submission Status": "حالة المعاملة",
    "Creator Name": "اسم المنشئ",
    "Owner Name": "اسم المالك",
    "Department Name": "اسم الإدارة",
    "Land usage": "استعمال الارض (نوع المخطط)",
    "Current Step": "اسم الخطوة",
    "Illustration of Land Usage": "رسم توضيحي لاستعمالات الأرض (نوع المخطط)",
    "اعتماد مخطط جديد processes": "معاملات اعتماد مخطط جديد ",
    processes: "معاملات",
    "Successfully retrieved data": "تم استرجاع البيانات بنجاح",
    "Succesfully deleted": "تم الحذف بنجاح",
    "Succesfully transfered": "تم قبول المعاملة المحولة بنجاح",
    refused: "تم رفض المعاملة المحولة بنجاح",
    "Failed to delete": "حدث خطأ",
    "Fields do not match": " كلمة المرور غير متطابقة",
    "No data found": "لا توجد نتائج",
    "An error occured, can not retrieve data": "حدث خطأ اثناء استرجاع البيانات",
    "Filter statistics by date": "بحث بالتاريخ",
    running: "جارى",
    Inbox: "المعاملات الواردة",
    RIDErrors: "مراجعة الهوية العقارية",
    DeedMomrahErrors: "مراجعة طلبات الصكوك",
    DeedMojErrors: "مراجعة اصدار الصكوك",
    Deedgenerated: "معاملات التحديث",
    Ridgenerated: "اصدار الصكوك",
    Outbox_Ordering: "التعميمات الصادرة",
    Inbox_Ordering: "التعميمات الواردة",
    Delayed: "المعاملات المتأخرة",
    Transferred: "المعاملات المحولة",
    Outbox: "المعاملات الصادرة",
    FollowingRequests: " متابعة المعاملات",
    Returned: "المعاملات المعادة",
    Signed: "المعاملات المعتمدة",
    Drafts: "معاملات تحت التجهيز",
    Paid: "المعاملات المدفوعة (الجاهزة للطباعة)",
    Unpaid: "المعاملات المعلقة",
    EngCompFreeze: "المكاتب الهندسية",
    "Late submissions": "المعاملات المتأخره",
    "Rejected submissions": "المعاملات المعتذر عنها",
    "Stopped submissions": "المعاملات المتوقفة",
    "Plan status": "حالة المخطط",
    Archive: "الارشيف",
    RequestedReporting: "تقارير معاملات الزوائد التنظيمية",
    allotmentRequestingReporting: "تقارير معاملات أراضي التخصيص",
    splitmergeRequestingReporting: "تقارير معاملات الفرز",
    propertycheckRequestingReporting: "تقارير معاملات فحص الملكية",
    e3tmadRequestingReporting: "تقارير معاملات اعتماد المخططات",

    ENGCOMP_ALERTS: "انذارات المكتب الهندسي",
    InfoPanel: "لوحة المعلومات",
    Finished: "المعاملات المنتهية", //al arshef
    Evaluations: "التقييمات",
    search: "بحث",
    "Create date": "تاريخ المعاملة",
    "Owner name": "اسم المالك / الجهة",
    "Owner name (municipality)": "اسم المالك / البلدية",
    "Department Name": "اسم الإدارة",
    "Step name": "اسم المرحلة",
    "in Time Count": "معاملات في وقتها",
    "warning Count": "معاملات قاربت على التأخير",
    "delayed Count": "معاملات متأخرة",
    "revision_tak": "مراجعه الفكرة التخطيطية",
    "approval_lagna": "اعتماد اللجنه الفنية",
    "matching_natural": "مطابقة على الطبيعه",
    "primary_approval": "الاعتماد المبدئى",
    "Infrastructure development": "تطوير البنية التحتية",
    "final_tabtery_approval": "طلب اعتماد نهائى تبتيرى",
    "final_approval": "  الاعتماد النهائى",
    Actions: "",
    Status: "حالة المعاملة",
    Type: "نوع المعاملة",
    Name: "الاسم",
    "Created at": "التاريخ",
    "Request number": "رقم المعاملة",
    "Warning Count": "عدد الإنذارات",
    "Create Autocad": "أصدار ملف الاتوكاد",
    View: "عرض",
    Refuse: "رفض",
    "Follow up": "متابعة",
    "Sak Update": "تحديث الصك",
    Print: "طباعة",
    InvoicePrint: "طباعة الفاتورة",
    Edit: "تعديل",
    Accept: "قبول",
    Continue: "إستكمال المعاملة",
    Delete: "حذف",
    "Committee report number": "رقم المحضر",
    "Export number": "رقم الصادر",
    "Creator name": "اسم المنشئ",
    "Engineering offices evaluations": "تقييمات المكاتب الهندسية",
    "Color key": "مفتاح المكتب",
    "Office name": "اسم المكتب",
    "Alerts number": "عدد الإنذارات",
    "Delete alert": "مسح الإنذارات",
    Statistics: "الإحصائيات",
    investment_Statistics: "مؤشرات",
    investment_Indicators: "مؤشرات الاستثمار",
    FOLLOWING_REQUESTS: "مؤشرات الاستثمار",
    team_indicators: "مؤشرات فريق العمل",
    "Illustration of all transactions": "رسم توضيحي لأنواع معاملات (*)",
    "Illustration of transactions types": "رسم توضيحي لمراحل المعاملة ",
    "Municipality name": "البلدية",
    steps: "الخطوات",
    Employeename: "اسم الموظف",
    delayedProcesses: "المعاملات المتأخرة",
    runningProcesses: "معاملات جارية",
    totalProcesses: "إجمالي المعاملات",
    canceledProcesses: "معاملات مرفوضة",
    rejectedProcesses: "معاملات معتذر عنها",
    finishedProcesses: "معاملات منتهية",
    stoppedProcesses: "معاملات متوقفة",
    finalApprovalProcesses: "معاملات الاعتماد النهائي",
    firstApprovalProcesses: "معاملات الاعتماد الأولي",
    underGoingProcesses: "معاملات تحت الاجراء",
    "Processes kind": "أنواع المعاملات",
    "Workflow kind": "أنواع مسارات العمل",
    "Number of processes": "	عدد المعاملات",
    "Illustration of all transactions by its kind":
      "رسم توضيحي للمعاملات بالنسبة لمسارات العمل",
    "Year period": "الفترة الزمنية",
    Inputs: "المدخلات",
    input: "المدخلات",
    output: "المخرجات",
    Outputs: "المخرجات",
    "Illustration of all transactions by year":
      "رسم توضيحي لمخرجات المعاملات بالنسبة لأنواعها بالفترة",
    "Illustration of all transactions FirstKind":
      "رسم توضيحي لمخرجات المعاملات لفرز الأراضي الفضاء",
    "Illustration of all transactions SecondKind":
      "رسم توضيحي لمخرجات المعاملات لفرز الوحدات العقارية",
    "Illustration of all transactions ThirdKind":
      "رسم توضيحي لمخرجات المعاملات لفرز الدوبلكسات",
    "Illustration of all submition data":
      "رسم توضيحي لأعداد المخططات بالبلديات",
    "Content data sorting services": "رسم توضيحي لأعداد المخططات بالبلديات",
    "Scalated hours": "المدة الزمنية لأجراء الخطوة",
    Running: "تحت الاجراء",
    FirstApproval: "معتمد اولي",
    firstApproval: "الاعتماد الأولي",
    firstApprovalNotes: "ملاحظات الاعتماد الأولي",
    FinalApproval: "معتمد نهائي",
    Stopped: "متوقف",
    Rejected: "مرفوض",
    "Are you sure?": "هل أنت متأكد من هذا الاجراء ؟",
    "Successfully global.SUBMIT request with number ":
      "تم  حفظ وارسال المعاملة بنجاح برقم",
    "Successfully global.REJECT request with number ": "تم رفض المعاملة رقم",
    "Successfully global.STOP request with number ": " تم ايقاف المعاملة رقم",
    "Successfully global.FINISH request with number ": " تم انهاء المعاملة رقم",
    "Successfully global.SENDAMANA request with number ":
      "تم ارسال المعاملة بنجاح رقم",
    "Successfully sent": "تم الارسال بنجاح",
    "Successfully approved": "تم الموافقة",
    "failed to send": "حدث خطأ",
  },
  modals: {
    WITH_EXPORT_NO: "موافقة",
    WITHOUT_EXPORT_NO: "موافقة بدون رقم الصادر",
    "Request number": "رقم المعاملة",
    "Enter request number": "ادخال رقم المعاملة",
    "Fields do not match": " كلمة المرور غير متطابقة",
    "Steps timeline": "الجدول الزمني لمراحل المعاملة",
    Yes: "نعم",
    No: "لا",
    Delete: "حذف",
    "Are you sure you want to delete?": "تأكيد الحذف؟",
    "Succesfully deleted": "تم الحذف",
    "Succesfully transfered": "تم التحويل بنجاح",
    "Failed to delete": "حدث خطأ",
    Cancel: "إغلاق",
    Gender: "النوع",
    Ok: "حفظ",
    "Send SMS": "ارسال رسالة",
    Owner: "المالك",
    Representative: "الوكيل",
    "Engineering office": "المكتب الهندسي",
    Message: "الرسالة",
    Assign: "توجيه",
    "Assign multi": " توجيه لمتعدد",
    transfer: "إحالة إلي",
    Reject: "اعتذار",
    Confirm: "تأكيد",
    Submit: "ارسال",
    "Send Amana": "ارسال للأمانة",
    "Submisison Submit": "رسالة تاكيدية",
    "Are you sure from this action?": "هل انت متاكد من هذا الاجراء ؟",
    Return: "اعادة توجيه",
    "Go to": "مخاطبة",
    sign: "توقيع",
    Back: "إنهاء المخاطبة",
    Approve: "موافقه و توجيه الى",
    Finish: "انهاء",
    "Are you sure?": "هل أنت متأكد؟",
    "set export number": "إصدار رقم الصادر",
    "Export number": "رقم الصادر",
    "Export date": "تاريخ الصادر",
    "Add a step": "اضافة خطوة",
    "Edit step": "تعديل الخطوة",
    Stop: "ايقاف",
    "Save edits": "حفظ التعديلات",
    "Continue submission": "استكمال المعاملة",
    "Successfully retrieved data": "تم استرجاع البيانات بنجاح",
    "An error occured, can not retrieve data": "حدث خطأ اثناء استرجاع البيانات",
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.SUBMIT request with number ":
      "تم  حفظ وارسال المعاملة بنجاح برقم",
    "Successfully global.REJECT request with number ": "تم رفض المعاملة رقم",
    "Successfully global.STOP request with number ": " تم ايقاف المعاملة رقم",
    "Successfully global.FINISH request with number ": " تم انهاء المعاملة رقم",
    "Successfully global.SENDAMANA request with number ":
      "تم ارسال المعاملة بنجاح رقم",
    "Successfully sent": "تم الارسال بنجاح",
    "Successfully approved": "تم الموافقة",
    "failed to send": "حدث خطأ",
    "Successfully created draft": "تم الحفظ بنجاح",
    "Failed to create draft": "حدث خطأ",
    "Successfully saved": "تم الحفظ بنجاح",
    "failed to save": "لم يتم الحفظ",
    "set draft name": "حفظ",
  },
  workFlow: {
    "Successfully global.GOTO request with number ":
      "تم مخاطبة المعاملة بنجاح برقم",
    "Successfully global.BACK request with number ":
      "تم إنهاء المخاطبة المعاملة بنجاح برقم",
    "Successfully global.ASSIGNMULTI request with number ":
      "تم توجيه المعاملة بنجاح برقم",
    "Successfully global.TRANSFER request with number ":
      "تم إحالة المعاملة بنجاح برقم",

    "Add new step": "إضافة خطوة",
    "Arrange steps": "ترتيب الخطوات",
    "Message content": "تفاصيل الرسالة",
    "Fields do not match": " كلمة المرور غير متطابقة",
  },
  admin: {
    "global.BACK": "السابق",
  },
};
